<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 profile-lists singlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
						<span>
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
								<path fill="currentColor" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></path>
							</svg>
						</span>

						<?php echo 'Leads'; ?>
					</div>
				</div>
			</div>

			<?php $groupData = Wo_GetMyPrivateGroups(); ?>
			<div class="page-margin wow_content">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_menu">
						<ul class="list-unstyled">
                            <li class=""><a href="<?php echo Wo_SeoLink('index.php?link1=private-groups'); ?>" data-ajax="?link1=private-leads"><?php echo $wo['lang']['lead_home'] ?></a></li>
                            <li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=leads-received-bid'); ?>" data-ajax="?link1=leads-received-bid"><?php echo $wo['lang']['lead_mylead']; ?>	</a></li>
                            <li class=""><a href="<?php echo Wo_SeoLink('index.php?link1=brows-normal-leads'); ?>" data-ajax="?link1=brows-normal-leads"><?php echo $wo['lang']['lead_browslead']; ?></a></li>
                            <li class=""><a href="<?php echo Wo_SeoLink('index.php?link1=leads-packages'); ?>" data-ajax="?link1=leads-packages"><?php echo $wo['lang']['lead_packages']; ?></a></li>
						</ul>
<!--						--><?php //if (count($groupData) == 0 && !empty($wo['private_categories'])) { ?>
							<a class="btn btn-main btn-mat btn-mat-raised" href="<?php echo Wo_SeoLink('index.php?link1=create-private-lead'); ?>" data-ajax="?link1=create-private-lead"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
									<path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path>
								</svg> <?php echo $wo['lang']['create'] ?>
							</a>
<!--						--><?php //} ?>
					</div>
				</div>
			</div>

            <div class="page-margin wow_content">
                <div class="wo_page_hdng pag_neg_padd pag_alone">
                    <div class="wo_page_hdng_menu">
                        <ul class="list-unstyled">
                            <li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=leads-received-bid'); ?>" data-ajax="?link1=leads-received-bid">Received Bids</a></li>
                            <li class=""><a href="<?php echo Wo_SeoLink('index.php?link1=leads-created'); ?>" data-ajax="?link1=leads-created">Created Leads</a></li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="col-lg-12">
                <table class="table DataTable table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <th><?php echo $wo['lang']['leads_received_bids_name']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_date']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_time']; ?> </th>
                        <th><?php echo $wo['lang']['leads_received_bids_details']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_amount']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_paynow']; ?></th>

                    </tr>
                    </thead>
                    <tbody id="mbrs">
                    <td><?php echo("Test") ?></td>

                    <td>
                        <span><?php echo("11/09/2010") ?></span>
                    </td>
                    <td><?php echo("2:30") ?></td>

                    <td>
                        <span>
                             <a href="<?php echo Wo_SeoLink('index.php?link1=lead-details'); ?>" data-ajax="?link1=lead-details" class="btn like-btn-text-sad"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M10,6.978c-1.666,0-3.022,1.356-3.022,3.022S8.334,13.022,10,13.022s3.022-1.356,3.022-3.022S11.666,6.978,10,6.978M10,12.267c-1.25,0-2.267-1.017-2.267-2.267c0-1.25,1.016-2.267,2.267-2.267c1.251,0,2.267,1.016,2.267,2.267C12.267,11.25,11.251,12.267,10,12.267 M18.391,9.733l-1.624-1.639C14.966,6.279,12.563,5.278,10,5.278S5.034,6.279,3.234,8.094L1.609,9.733c-0.146,0.147-0.146,0.386,0,0.533l1.625,1.639c1.8,1.815,4.203,2.816,6.766,2.816s4.966-1.001,6.767-2.816l1.624-1.639C18.536,10.119,18.536,9.881,18.391,9.733 M16.229,11.373c-1.656,1.672-3.868,2.594-6.229,2.594s-4.573-0.922-6.23-2.594L2.41,10l1.36-1.374C5.427,6.955,7.639,6.033,10,6.033s4.573,0.922,6.229,2.593L17.59,10L16.229,11.373z" ></path></svg></a>
						</span>
                    </td>
                    <td><?php echo("$200") ?></td>

                    <td>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M14.781,14.347h1.738c0.24,0,0.436-0.194,0.436-0.435v-1.739c0-0.239-0.195-0.435-0.436-0.435h-1.738c-0.239,0-0.435,0.195-0.435,0.435v1.739C14.347,14.152,14.542,14.347,14.781,14.347 M18.693,3.045H1.307c-0.48,0-0.869,0.39-0.869,0.869v12.17c0,0.479,0.389,0.869,0.869,0.869h17.387c0.479,0,0.869-0.39,0.869-0.869V3.915C19.562,3.435,19.173,3.045,18.693,3.045 M18.693,16.085H1.307V9.13h17.387V16.085z M18.693,5.653H1.307V3.915h17.387V5.653zM3.48,12.608h7.824c0.24,0,0.435-0.195,0.435-0.436c0-0.239-0.194-0.435-0.435-0.435H3.48c-0.24,0-0.435,0.195-0.435,0.435C3.045,12.413,3.24,12.608,3.48,12.608 M3.48,14.347h6.085c0.24,0,0.435-0.194,0.435-0.435s-0.195-0.435-0.435-0.435H3.48c-0.24,0-0.435,0.194-0.435,0.435S3.24,14.347,3.48,14.347"></path></svg>
                    </td>

                    <!--                    --><?php //echo '<tr> <td colspan="7" class="text-center" style="padding:40px 40px;" >' . $wo['lang']['leads_received_bids_nodata'] . '</td></tr>'; ?>

                    </tbody>
                </table>
            </div>
            <br>


			<div class="row">
				<?php if (count($groupData) > 0) {
					$wo['group']['Wo_GroupSug'] = ($groupData['type'] == 'join') ? true : false;
					$wo['group'] = $groupData['group'];
					echo Wo_LoadPage('private_group/group-list');
				} else {
					echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></path></svg>' . $wo['lang']['no_groups_found'] . '</div>';
				} ?>

				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- .row -->
</div>