<div class="page-margin">
    <div class="row">
        <div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
        <div class="col-md-7 profile-lists singlecol">
            <div class="page-margin wow_content mt-0">
                <div class="wo_page_hdng pag_neg_padd pag_alone">
                    <div class="wo_page_hdng_innr big_size">
						<span>
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
								<path fill="currentColor" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></path>
							</svg>
						</span>

                        <?php echo 'Leads'; ?>
                    </div>
                </div>
            </div>

            <?php
            $leadData = Wo_GetMyPrivateLeads();
            ?>
            <?php $groupData = Wo_GetMyPrivateGroups(); ?>
            <div class="page-margin wow_content">
                <div class="wo_page_hdng pag_neg_padd pag_alone">
                    <div class="wo_page_hdng_menu">
                        <ul class="list-unstyled">
                            <li class=""><a href="<?php echo Wo_SeoLink('index.php?link1=private-groups'); ?>" data-ajax="?link1=private-leads"><?php echo $wo['lang']['lead_home'] ?></a></li>
                            <li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=leads-received-bid'); ?>" data-ajax="?link1=leads-received-bid"><?php echo $wo['lang']['lead_mylead']; ?>	</a></li>
                            <li class=""><a href="<?php echo Wo_SeoLink('index.php?link1=brows-normal-leads'); ?>" data-ajax="?link1=brows-normal-leads"><?php echo $wo['lang']['lead_browslead']; ?></a></li>
                            <li class=""><a href="<?php echo Wo_SeoLink('index.php?link1=leads-packages'); ?>" data-ajax="?link1=leads-packages"><?php echo $wo['lang']['lead_packages']; ?></a></li>
                        </ul>
                        <!--						--><?php //if (count($groupData) == 0 && !empty($wo['private_categories'])) { ?>
                        <a class="btn btn-main btn-mat btn-mat-raised" href="<?php echo Wo_SeoLink('index.php?link1=create-private-lead'); ?>" data-ajax="?link1=create-private-lead"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path>
                            </svg> <?php echo $wo['lang']['create'] ?>
                        </a>
                        <!--						--><?php //} ?>
                    </div>
                </div>
            </div>

            <div class="page-margin wow_content">
                <div class="wo_page_hdng pag_neg_padd pag_alone">
                    <div class="wo_page_hdng_menu">
                        <ul class="list-unstyled">
                            <li class=""><a href="<?php echo Wo_SeoLink('index.php?link1=leads-received-bid'); ?>" data-ajax="?link1=leads-received-bid">Received Bids</a></li>
                            <li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=leads-created'); ?>" data-ajax="?link1=leads-created">Created Leads</a></li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="col-lg-12">
                <table class="table DataTable table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <th><?php echo $wo['lang']['leads_received_bids_name']; ?></th>
                        <th><?php echo $wo['lang']['tag_key']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_date']; ?></th>
<!--                        <th>--><?php //echo $wo['lang']['leads_received_bids_time']; ?><!-- </th>-->
                        <th><?php echo $wo['lang']['leads_received_bids_details']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_amount']; ?></th>
                        <th><?php echo $wo['lang']['status']; ?></th>

                    </tr>
                    </thead>
                    <tbody id="mbrs">
                    <?php if (count($leadData) > 0) {
                        foreach ($leadData['lead'] as $lead){ ?>
                            <tr>
                                <td><?php echo $lead['service_name']; ?></td>
                                <td><span><?php echo $lead['tag_keyword']; ?></span></td>
                                <td><?php echo $lead['created_at']; ?></td>
                                <td><?php echo $lead['details']; ?></td>
                                <td><?php echo $lead['budget']; ?></td>
                                <td>
                                    <i class="fa fa-check-circle-o"></i>
                                    <span><a href="<?php echo Wo_SeoLink('index.php?link1=created-lead-details'.$lead['id']); ?>" data-ajax="?link1=created-lead-details&group=<?php echo $lead['id']; ?>" class="btn like-btn-text-sad"><i class="fa fa-eye"></i></a></span>
<!--                                    <span><a href="--><?php //echo Wo_SeoLink('index.php?link1=private-lead-setting&group='.$lead['id']); ?><!--" data-ajax="?link1=private-lead-setting&group=--><?php //echo $lead['id']; ?><!--" class="btn"> <i class="fa fa-eye"></i></a></span>-->
                                </td>
                            </tr>
                       <?php }
                    } else {
                        echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></path></svg>' . $wo['lang']['no_groups_found'] . '</div>';
                    } ?>


                    <!--                    --><?php //echo '<tr> <td colspan="7" class="text-center" style="padding:40px 40px;" >' . $wo['lang']['leads_received_bids_nodata'] . '</td></tr>'; ?>

                    </tbody>
                </table>
            </div>
            <br>
        </div>
    </div>
    <!-- .row -->
</div>
<script>
    $( document ).ready(function() {
        $('.DataTable').DataTable();
    })
</script>