<div class="container-fluid">
    <div class="block-header">
        <h2>Normal Leads > Manage Normal Leads </h2>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Normal Leads</h2>
                </div>
                <div class="body">
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Service Name</th>
                                <th>Tags</th>
                                <th>Service Location</th>
                                <th>BUdget</th>
                                <th>Details</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $sections = Wo_Getnormallead(array('forums'=>false, 'limit'=>500000, 'order_by' => 'DESC')) ?>
                            <?php foreach ($sections as $section): ?>
                                <tr data-rmd-section-ident="<?php echo $section['id']; ?>">
                                    <td><?php echo $section['id']; ?></td>
                                    <td><?php echo $section['service_name']; ?></td>
                                    <td><?php echo $section['tags']; ?></td>
                                    <td><?php echo $section['service_location']; ?></td>
                                    <td><?php echo $section['budget']; ?></td>
                                    <td><?php echo $section['detail']; ?></td>
                                    <td>
                                        <button class="btn btn-danger delete-section waves-effect waves-light" id="<?php echo $section['id'];?>">
                                            DELETE
                                        </button>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<div class="modal fade" id="delete-section">
    <div class="modal-dialog">
        <div class="modal-content modal-col-red">
            <div class="modal-header">
                <h4 class="modal-title"><i class="fa fa-exclamation-circle"></i> Delete Lead</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this Lead?</p>
            </div>
            <div class="modal-footer">
                <button  type="button" onclick="Wo_Delnormallead($('#delete-section').attr('data-section-ident'))" class="btn btn-link">DELETE</button>
                <button  type="button" class="btn btn-link" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('table').DataTable();
    });
    $(document).on('click', ".delete-section", function(event) {
        event.preventDefault();
        $("#delete-section").attr('data-section-ident', $(this).attr('id')).modal('show');
    });
    function Wo_Delnormallead(id) {
        if (!id) {
            return false;
        } else {
            $("#delete-section").modal("hide");
            $("[data-rmd-section-ident='" + id + "']").slideUp(function() {
                $(this).remove()
            });
            $.ajax({
                type: "GET",
                url: Wo_Ajax_Requests_File(),
                data: {
                    id: id,
                    f: 'delete-normal-lead'
                },
                dataType: 'json'
            });
        }
    }
</script>