<div class="container-fluid">
    <div class="block-header">
        <h2>Product Category > Edit Product Category</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="header">
                    <h2>Edit Product Category</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success email-settings-alert"></div>
                    <?php
                        $ProductCategory = Wo_ProductCategoryFromByid($_GET['id']);
                    ?>
                    <form class="email-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="lang" name="category" value="<?php echo $ProductCategory['name'];?>" class="form-control">
                                <label class="form-label">Product Category</label>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <input type="hidden" name="id" value="<?php echo $ProductCategory['id'];?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Add Product Category</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
    <script>

        $(function() {
            var form_email_settings = $('form.email-settings');
            form_email_settings.ajaxForm({
                url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_product_category',
                beforeSend: function() {
                    form_email_settings.find('button').text('Please wait..');
                },
                success: function(data) {
                    if (data.status == 200) {
                        $("html, body").animate({ scrollTop: 0 }, "slow");
                        $('.email-settings-alert').html('<i class="fa fa-check"></i> Product Category successfully updated');
                        setTimeout(function () {
                            window.location.href = '<?php echo Wo_LoadAdminLinkSettings('manage-product-category'); ?>';
                        }, 1000);
                    }
                    form_email_settings.find('button').text('Add Language');
                }
            });

        });
    </script>