<div class="page-margin">
	<div class="wow_content wow_sett_content">
		<div class="wo_page_hdng pag_neg_padd">
			<div class="wo_page_hdng_innr">
				<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
						<path fill="currentColor" d="M22.7,19L13.6,9.9C14.5,7.6 14,4.9 12.1,3C10.1,1 7.1,0.6 4.7,1.7L9,6L6,9L1.6,4.7C0.4,7.1 0.9,10.1 2.9,12.1C4.8,14 7.5,14.5 9.8,13.6L18.9,22.7C19.3,23.1 19.9,23.1 20.3,22.7L22.6,20.4C23.1,20 23.1,19.3 22.7,19Z"></path>
					</svg></span> <?php echo $wo['lang']['general_setting']; ?>
			</div>
		</div>
		<form class="setting-general-form form-horizontal" method="post">
			<div class="setting-general-alert"></div>

			<div class="wow_form_fields">
				<label for="group_title"><?php echo $wo['lang']['group_name']; ?></label>
				<input name="group_title" id="group_title" type="text" value="<?php echo $wo['setting']['group_title'] ?>" autocomplete="off">
			</div>

			<div class="wow_form_fields">
				<label for="group_name"><?php echo $wo['lang']['group']; ?> URL</label>
				<div class="input-group">
					<span class="input-group-addon"><?php echo $wo['config']['site_url']; ?>/</span>
					<input id="group_name" name="group_name" type="text" value="<?php echo $wo['setting']['group_name'] ?>" onkeyup="Wo_CheckGroupname(this.value, <?php echo $wo['setting']['id']; ?>);" autocomplete="off">
				</div>
				<span class="help-block checking"></span>
			</div>
			<div class="wow_form_fields">
				<label for="about"><?php echo $wo['lang']['description']; ?></label>
				<?php $text = br2nl($wo['setting']['about']); ?>
				<textarea id="about" name="about" rows="4"><?php echo $text; ?></textarea>
			</div>

			<div class="wow_form_fields">
				<label for="address"><?php echo $wo['lang']['location']; ?></label>
				<input id="address" name="address" type="text" value="<?php echo $wo['setting']['address'] ?>">
			</div>

			<?php if (Wo_CountPrivateGroupsNotCategories($wo['setting']['id']) > 0) { ?>
				<div class="row" style="margin-bottom: 20px;">
					<div class="col-md-12">
						<div class="multiple-select">
							<label for="group_employee_job_category"><?php echo $wo['lang']['employee_category']; ?></label>
							<select name="group_employee_job_category[]" id="group_employee_job_category" multiple>
								<?php foreach (Wo_GetPrivateGroupsNotCategories($wo['setting']['id']) as $id => $category) { ?>
									<?php foreach ($category as $jobcategory) { ?>
										<option value="<?php echo $jobcategory['id'] ?>"><?php echo $jobcategory['lang']; ?></option>
									<?php } ?>
								<?php } ?>
							</select>
						</div>
					</div>
				</div>
			<?php } ?>

			<div class="d-flex align-items-center justify-content-between">
				<div>
					<?php echo $wo['lang']['suggest_admin']; ?>
				</div>

				<div>
					<button type="button" class="btn btn-main setting-panel-mdbtn" onclick="Wo_SuggestBox();"><?php echo $wo['lang']['suggest']; ?></button>
				</div>
			</div>

			<div class="text-center">
				<button class="btn btn-main btn-mat btn-mat-raised add_wow_loader" type="submit"><?php echo $wo['lang']['save']; ?></button>
			</div>
			<input type="hidden" name="group_id" value="<?php echo $wo['setting']['id']; ?>">
			<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
		</form>
	</div>
</div>

<div class="modal fade" id="suggest_categories_modal" role="dialog" data-keyboard="false" style="overflow-y: auto;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
							<line x1="18" y1="6" x2="6" y2="18"></line>
							<line x1="6" y1="6" x2="18" y2="18"></line>
						</svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['suggest'] ?></h4>
			</div>
			<form class="form form-horizontal" method="post" id="suggest_categories_form" action="#">
				<div class="modal-body dt_bank_trans_modal">
					<div id="blog-alert"></div>

					<?php echo $wo['config']['suggest_admin']; ?>

					<div class="wow_form_fields">
						<label for="suggestions"><?php echo $wo['lang']['suggest']; ?></label>
						<textarea id="suggestions" name="suggestions" rows="4" placeholder="<?php echo $wo['lang']['suggest_help']; ?>"></textarea>
					</div>

					<input name="group_id" type="hidden" value="<?php echo $wo['setting']['id']; ?>" class="hidden">
					<input name="category_id" type="hidden" value="<?php echo $wo['setting']['category_id']; ?>" class="hidden">
				</div>
				<div class="modal-footer">
					<button class="btn btn-main btn-mat btn-mat-raised add_wow_loader" type="submit"><?php echo $wo['lang']['suggest']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	function Wo_SuggestBox() {
		$('#suggest_categories_modal').modal({
			show: true
		});
	}

	var pac_input = document.getElementById('address');
	(function pacSelectFirst(input) {
		// store the original event binding function
		var _addEventListener = (input.addEventListener) ? input.addEventListener : input.attachEvent;

		function addEventListenerWrapper(type, listener) {
			// Simulate a 'down arrow' keypress on hitting 'return' when no pac suggestion is selected,
			// and then trigger the original listener.
			if (type == "keydown") {
				var orig_listener = listener;
				listener = function(event) {
					var suggestion_selected = $(".pac-item-selected").length > 0;
					if (event.which == 13 && !suggestion_selected) {
						var simulated_downarrow = $.Event("keydown", {
							keyCode: 40,
							which: 40
						});
						orig_listener.apply(input, [simulated_downarrow]);
					}
					orig_listener.apply(input, [event]);
				};
			}
			// add the modified listener
			_addEventListener.apply(input, [type, listener]);
		}
		if (input.addEventListener)
			input.addEventListener = addEventListenerWrapper;
		else if (input.attachEvent)
			input.attachEvent = addEventListenerWrapper;
	})(pac_input);

	<?php if ($wo['config']['google_map']) { ?>
		$(function() {
			var autocomplete = new google.maps.places.Autocomplete(pac_input);
		});
	<?php } ?>

	$(function() {
		<?php if (Wo_CountPrivateGroupsNotCategories($wo['setting']['id']) > 0) { ?>
			$('#group_employee_job_category').multipleSelect({
				selectAll: false
			});
		<?php } ?>

		$('#suggest_categories_form').ajaxForm({
			url: Wo_Ajax_Requests_File() + '?f=private_group&s=suggest_categories',
			beforeSend: function() {
				$('#suggest_categories_form').find('.add_wow_loader').addClass('btn-loading');
			},
			success: function(data) {
				if (data.status == 200) {
					$('#blog-alert').html('<div class="alert alert-success">' + data.message + '</div>');
					setTimeout(function() {
						$("#blog-alert").html('');
						$('#suggestions').val('');
						$('#suggest_categories_modal').modal('hide');
					}, 2000);
				} else {
					$('#blog-alert').html('<div class="alert alert-danger">' + data.message + '</div>');
					setTimeout(function() {
						$("#blog-alert").html('');
					}, 2000);
				}
				$('#suggest_categories_form').find('.add_wow_loader').removeClass('btn-loading');
			}
		});

		$('form.setting-general-form').ajaxForm({
			url: Wo_Ajax_Requests_File() + '?f=private_group&s=update_general_settings',
			beforeSend: function() {
				$('.setting-general-form').find('.add_wow_loader').addClass('btn-loading');
			},
			success: function(data) {
				scrollToTop();
				if (data.status == 200) {
					$('.setting-general-alert').html('<div class="alert alert-success">' + data.message + '</div>');
					$('.alert-success').fadeIn('fast', function() {
						$(this).delay(2500).slideUp(500, function() {
							$(this).remove();
							location.reload();
						});
					});
				} else {
					var errors = data.errors.join("<br>");
					$('.setting-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
					$('.alert-danger').fadeIn(300);
				}
				$('.setting-general-form').find('.add_wow_loader').removeClass('btn-loading');
			}
		});
	});
</script>