<?php
$page_name = '';
$page_icon = '';
switch ($wo['active']) {
		case 1:
			$page_name = "leads";
			break;
		case 2:
			$page_name = $wo['lang']['going'];
			break;
		case 3:
			$page_name = $wo['lang']['invited'];
			break;
		case 4:
			$page_name = $wo['lang']['interested'];
			break;
		case 5:
			$page_name = $wo['lang']['past'];
			break;
		case 6:
			$page_name = $wo['lang']['create'];
			break;
		case 7:
			$page_name = $wo['lang']['my_events'];
			break;
		default:
	}
?>

<div class="page-margin">
	<div class="row h-m0">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 profile-lists singlecol">
			<div class="wo_my_pages events-content-wrapper">
				<div class="page-margin wow_content mt-0">
					<div class="wo_page_hdng pag_neg_padd pag_alone">
						<div class="wo_page_hdng_innr big_size">
							<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,12H12V17H17V12Z"></path></svg></span> <?php echo "Leads"; ?>
						</div>
					</div>
				</div>
				<div class="page-margin wow_content">
					<div class="wo_page_hdng pag_neg_padd pag_alone">
						<div class="wo_page_hdng_menu">
							<ul class="list-unstyled">
								<li class="<?php echo ($wo['active'] == "1" ? "active" : "")?>"><a href="<?php echo Wo_SeoLink('index.php?link1=leads'); ?>" data-ajax="?link1=leads"><?php echo $wo['lang']['lead_home'] ?></a></li>
								<li class="<?php echo ($wo['active'] == "2" ? "active" : "")?>"><a href="<?php echo Wo_SeoLink('index.php?link1=leads-going'); ?>" data-ajax="?link1=leads-going"><?php echo $wo['lang']['lead_mylead']; ?>	</a></li>
								<li class="<?php echo ($wo['active'] == "3" ? "active" : "")?>"><a href="<?php echo Wo_SeoLink('index.php?link1=leads-invited'); ?>" data-ajax="?link1=leads-invited"><?php echo $wo['lang']['lead_browslead']; ?></a></li>
								<li class="<?php echo ($wo['active'] == "4" ? "active" : "")?>"><a href="<?php echo Wo_SeoLink('index.php?link1=leads-interested'); ?>" data-ajax="?link1=leads-interested"><?php echo $wo['lang']['lead_packages']; ?></a></li>

<!--                                -->
<!--                                <li class="--><?php //echo ($wo['active'] == "5" ? "active" : "")?><!--"><a href="--><?php //echo Wo_SeoLink('index.php?link1=leads-past'); ?><!--" data-ajax="?link1=leads-past">--><?php //echo $wo['lang']['events_past']; ?><!--</a></li>-->
<!--								<li class="--><?php //echo ($wo['active'] == "7" ? "active" : "")?><!--"><a href="--><?php //echo Wo_SeoLink('index.php?link1=my-leads'); ?><!--" data-ajax="?link1=my-events">--><?php //echo $wo['lang']['my_events']; ?><!--</a></li>-->
<!--							-->
                            </ul>
							<a class="btn btn-main btn-mat btn-mat-raised" href="<?php echo Wo_SeoLink('index.php?link1=create-lead');?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path></svg> <?php echo $wo['lang']['create'] ?></a>
						</div>
					</div>
				</div>
				<div class="row h-m0">