<div class="sun_sett_sidebar group">
	<ul class="list-unstyled">
		<?php if ($wo['setting']['user_id'] == $wo['user']['id'] || Wo_IsCanPrivateGroupUpdate($wo['setting']['id'], 'general')) { ?>
			<li class="<?php echo ($wo['setting_page'] == 'general-setting') ? 'active' : ''; ?>">
				<a href="<?php echo Wo_SeoLink('index.php?link1=private-g&group=' . $wo['setting']['group_name'] . '&link3=general-setting'); ?>" data-ajax="?link1=private-g&group=<?php echo $wo['setting']['group_name'] ?>&link3=general-setting">
					<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings">
							<circle cx="12" cy="12" r="3"></circle>
							<path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path>
						</svg></span> <?php echo $wo['lang']['general']; ?>
				</a>
			</li>
		<?php } ?>
		<?php if ($wo['setting']['user_id'] == $wo['user']['id'] || Wo_IsCanPrivateGroupUpdate($wo['setting']['id'], 'avatar')) { ?>
			<li class="<?php echo ($wo['setting_page'] == 'avatar-setting') ? 'active' : ''; ?>">
				<a href="<?php echo Wo_SeoLink('index.php?link1=private-g&group=' . $wo['setting']['group_name'] . '&link3=avatar-setting'); ?>" data-ajax="?link1=private-g&group=<?php echo $wo['setting']['group_name'] ?>&link3=avatar-setting">
					<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-image">
							<rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
							<circle cx="8.5" cy="8.5" r="1.5"></circle>
							<polyline points="21 15 16 10 5 21"></polyline>
						</svg></span> <?php echo $wo['lang']['avatar_and_cover']; ?>
				</a>
			</li>
		<?php } ?>
		<?php if ($wo['setting']['user_id'] == $wo['user']['id'] || Wo_IsCanPrivateGroupUpdate($wo['setting']['id'], 'members')) { ?>
			<li class="<?php echo ($wo['setting_page'] == 'group-members') ? 'active' : ''; ?>">
				<a href="<?php echo Wo_SeoLink('index.php?link1=private-g&group=' . $wo['setting']['group_name'] . '&link3=group-members'); ?>" data-ajax="?link1=private-g&group=<?php echo $wo['setting']['group_name'] ?>&link3=group-members">
					<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users">
							<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
							<circle cx="9" cy="7" r="4"></circle>
							<path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
							<path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
						</svg></span> <?php echo $wo['lang']['members']; ?>
				</a>
			</li>
		<?php } ?>
		<?php if ($wo['setting']['user_id'] == $wo['user']['id'] || Wo_IsCanPrivateGroupUpdate($wo['setting']['id'], 'analytics')) { ?>
			<li class="<?php echo ($wo['setting_page'] == 'analytics') ? 'active' : ''; ?>">
				<a href="<?php echo Wo_SeoLink('index.php?link1=private-g&group=' . $wo['setting']['group_name'] . '&link3=analytics'); ?>" data-ajax="?link1=private-g&group=<?php echo $wo['setting']['group_name'] ?>&link3=analytics">
					<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-download">
							<polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline>
							<polyline points="17 6 23 6 23 12"></polyline>
						</svg></span> <?php echo $wo['lang']['group_analytics']; ?>
				</a>
			</li>
		<?php } ?>
		<?php if ($wo['setting']['user_id'] == $wo['user']['id'] || Wo_IsCanPrivateGroupUpdate($wo['setting']['id'], 'delete_group')) { ?>
			<li class="<?php echo ($wo['setting_page'] == 'delete-group') ? 'active' : ''; ?>">
				<a href="<?php echo Wo_SeoLink('index.php?link1=private-g&group=' . $wo['setting']['group_name'] . '&link3=delete-group'); ?>" data-ajax="?link1=private-g&group=<?php echo $wo['setting']['group_name'] ?>&link3=delete-group">
					<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
							<polyline points="3 6 5 6 21 6"></polyline>
							<path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
							<line x1="10" y1="11" x2="10" y2="17"></line>
							<line x1="14" y1="11" x2="14" y2="17"></line>
						</svg></span> <?php echo $wo['lang']['delete_group']; ?>
				</a>
			</li>
		<?php } ?>
	</ul>
</div>