Hi there,
<br><br>
You have received an invitation request from your friend <a style="color:<?php echo $wo['config']['btn_background_color']; ?>" href="<?php echo $wo['user']['url'] ?>"><?php echo $wo['user']['name']; ?></a> to join his private group <a style="color:<?php echo $wo['config']['btn_background_color']; ?>" href="<?php echo $wo['config']['site_url'] . '/join-private-group?token=' . $wo['token'] . '&ref=' . $wo['group_data']['group_name'] ?>"><?php echo $wo['group_data']['group_title'] ?></a>.<br><br>
<a style="color:<?php echo $wo['config']['btn_background_color']; ?>" href="<?php echo $wo['config']['site_url'] . '/join-private-group?token=' . $wo['token'] . '&ref=' . $wo['group_data']['group_name'] ?>">Join in this private circle !</a>
<br><br>
<?php echo $wo['config']['siteName'] ?> Team.
<br>
Best regards.