<div class="container-fluid">
    <div class="block-header">
        <h2>Packages > Manage Packages </h2>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Packages</h2>
                </div>
                <div class="body">
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Package Name</th>
                                <th>No.of Bids</th>
                                <th>Pricing</th>
                                <th>Exp.Year</th>
                                <th>Exp.Month</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $sections = Wo_GetPackages(array('forums'=>false, 'limit'=>500000, 'order_by' => 'DESC')) ?>
                            <?php foreach ($sections as $section): ?>
                                <tr data-rmd-section-ident="<?php echo $section['id']; ?>">
                                    <td><?php echo $section['id']; ?></td>
                                    <td><?php echo $section['name']; ?></td>
                                    <td><?php echo $section['send_limit']; ?></td>
                                    <td><?php echo $section['pricing']; ?></td>
                                    <td><?php echo $section['year']; ?></td>
                                    <td><?php echo $section['month']; ?></td>
                                    <td>
                                        <button class="btn btn-danger delete-section waves-effect waves-light" id="<?php echo $section['id'];?>">
                                            DELETE
                                        </button>
                                        <button class="btn btn-warning waves-effect waves-light" onclick="edit_package('<?php echo $section['id'] ?>')">
                                            Edit
                                        </button>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<div class="modal fade" id="delete-section">
    <div class="modal-dialog">
        <div class="modal-content modal-col-red">
            <div class="modal-header">
                <h4 class="modal-title"><i class="fa fa-exclamation-circle"></i> Delete Lead</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this Package?</p>
            </div>
            <div class="modal-footer">
                <button  type="button" onclick="Wo_Delpackage($('#delete-section').attr('data-section-ident'))" class="btn btn-link">DELETE</button>
                <button  type="button" class="btn btn-link" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="editcategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal_content_back">
            <div class="modal-header">
                <h5 class="modal-title" id="editcategoryModalLabel">Edit Package</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="edit_category_form_alert"></div>
                <form class="edit_category_lang" method="POST" id="modal-body-langs">
                    <div class="data_lang">
                        <input class="form-control" type="hidden" id="id" name="id" value="">
                        <label>Package Name</label>
                        <input class="form-control" type="text"id="name" name="name"  value="">
                        <label>No.of Bids</label>
                        <input class="form-control" type="text"id="limit" name="limit" value="">
                        <label>Pricing Plan</label>
                     <input class="form-control" type="text" id="pricing" name="pricing"  value="">

                      <label>Exp.Year</label>
                        <input class="form-control" type="text"id="year" name="year" value="">
                        <label>Exp.Month</label>
                     <input class="form-control" type="text" id="month" name="month"  value="">

                    <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    <input type="hidden" name="id_of_key" id="id_of_key" value="">
                    </div>
                </form>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal">CLOSE</button>
                <button type="button" class="btn btn-primary" id="save_edited_category" onclick="update_package()">SAVE CHANGES</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('table').DataTable();
    });
    $(document).on('click', ".delete-section", function(event) {
        event.preventDefault();
        $("#delete-section").attr('data-section-ident', $(this).attr('id')).modal('show');
    });
    function Wo_Delpackage(id) {
        if (!id) {
            return false;
        } else {
            $("#delete-section").modal("hide");
            $("[data-rmd-section-ident='" + id + "']").slideUp(function() {
                $(this).remove()
            });
            $.ajax({
                type: "GET",
                url: Wo_Ajax_Requests_File(),
                data: {
                    id: id,
                    f: 'delete-package'
                },
                dataType: 'json'
            });
        }
    }

    function edit_package(id) {
        $('#id_of_key').val(id);
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_package', {package_id: id}, function(data, textStatus, xhr) {
            if (data.status == 200) {
                // $('.data_lang').html(data.package);
                $('#id').val(data.package['id']);
                $('#name').val(data.package['name']);
                $('#limit').val(data.package['send_limit']);
                $('#pricing').val(data.package['pricing']);
                $('#year').val(data.package['year']);
                $('#month').val(data.package['month']);
                $('#editcategoryModal').modal();
            }
        });
    }

     function update_package() {
        let package_id=$('#id').val();
        let package_name=$('#name').val();
        let package_limit=$('#limit').val();
        let package_pricing=$('#pricing').val();
        let year=$('#year').val();
        let month=$('#month').val();

        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_package',
        {package_id: package_id,package_name:package_name,package_limit:package_limit,package_pricing:package_pricing,
        year:year,month:month},
         function(data, textStatus, xhr) {
            setTimeout(function(){// wait for 5 secs(2)
           location.reload(); // then reload the page.(3)
      }, 500);

        });
    }
</script>

