<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M19 19V8H5V19H19M16 1H18V3H19C20.11 3 21 3.9 21 5V19C21 20.11 20.11 21 19 21H5C3.89 21 3 20.1 3 19V5C3 3.89 3.89 3 5 3H6V1H8V3H16V1M11 9.5H13V12.5H16V14.5H13V17.5H11V14.5H8V12.5H11V9.5Z"></path></svg></span> <?php echo $wo['lang']['create_lead'];?>
					</div>
				</div>
			</div>

			<div class="page-margin wow_content wow_sett_content">
				<form class="form form-horizontal" method="post" id="form-create-lead">
					<div class="wow_form_fields">
						<label for="lead-name"><?php echo $wo['lang']['ser_name']; ?></label>
						<input id="lead-name" placeholder="<?php echo $wo['lang']['ser_name']; ?>" name="service_name" type="text">
					</div>
                    <div class="wow_form_fields">
                        <label for="lead-tag-keyword"><?php echo $wo['lang']['tag_key']; ?></label>
                        <input id="lead-tag-keyword" placeholder="<?php echo $wo['lang']['tag_key_placeholder']; ?>" name="tag_keyword" type="text">
                    </div>

                    <div class="row h-m0">
                            <div class="col-md-6 wow_form_fields h-p0">
                                <label class="col-md-12" for="category"><?php echo $wo['lang']['category']; ?> *</label>
                                <div class="col-md-12">
                                    <select name="group_category" id="category" class="form-control" onchange="GetGroupJobCategory(this)">
                                        <?php foreach ($wo['private_categories'] as $category_id => $category_name) { ?>
                                            <option value="<?php echo $category_id ?>"><?php echo $category_name; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <?php if (!empty($wo['private_job_categories'])) { ?>
                                <div class="wow_form_fields col-lg-6 h-p0">
                                    <label class="col-md-12" for="group_job_category"><?php echo $wo['lang']['job_category']; ?> *</label>
                                    <div class="col-md-12">
                                        <select name="job_category" id="group_job_category" class="form-control" onchange="Wo_ChangeOptions(this)">
                                            <?php if (!empty($wo['private_job_categories'][array_keys($wo['private_categories'])[0]])) {
                                                foreach ($wo['private_job_categories'][array_keys($wo['private_categories'])[0]] as $id => $sub_category) { ?>
                                                    <option value="<?php echo $sub_category['id'] ?>"><?php echo $sub_category['lang']; ?></option>
                                                <?php }
                                            } ?>
                                        </select>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    <div class="row h-m0">
                            <div class="col-md-6 wow_form_fields h-p0">
                                <label class="col-md-12" for="category"><?php echo $wo['lang']['product_category']; ?> *</label>
                                <div class="col-md-12">
                                    <select name="product_category" id="category" class="form-control" onchange="GetGroupJobCategory(this)">
                                        <?php
                                        $productCategories = Wo_ProductCategoryFromDB();
                                        foreach ($productCategories as $productCategory) { ?>
                                            <option value="<?php echo $productCategory['id'] ?>"><?php echo $productCategory['name']; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 wow_form_fields">
                                <label for="lead-start"><?php echo $wo['lang']['lead_budget']; ?></label>


                                <input type="text" id="" placeholder="<?php echo $wo['lang']['lead_budget_placeholder']; ?>" class="" name="budget">
                            </div>
                        </div>


                    <div class="wow_form_fields">
                        <label for="lead-locat"><?php echo $wo['lang']['service_location'];?></label>
                        <input id="lead-location" name="service_location" type="text">
                    </div>
<!--                    --><?php //if ($wo['config']['google_map'] == 1) { ?>
<!--                        <div id="review-location">-->
<!--                            <div id="place"></div>-->
<!--                        </div>-->
<!--                    --><?php //} ?>
					<div class="wow_form_fields">
						<label for="lead-description"><?php echo $wo['lang']['lead_details']; ?></label>
						<textarea name="details" id="lead-description" placeholder="<?php echo $wo['lang']['lead_details_placeholder']; ?>" rows="5"></textarea>
					</div>
					
					<div class="setting-update-alert" id="lead-alert"></div>
					
					<div class="text-center">
						<a class="btn btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>" data-ajax="?link1=my-events">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $wo['lang']['go_back'];?>
						</a>
						<button class="btn btn-main btn-mat btn-mat-raised add_wow_loader" type="submit"><?php echo $wo['lang']['publish']; ?></button>
					</div>
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				</form>
                <div id="lead-alert"></div>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery-ui-timepicker-addon@1.6.3/dist/jquery-ui-timepicker-addon.min.js"></script>
<script>
	<?php if ($wo['config']['google_map'] == 1) { ?>
      	$(document).on('change', '#event-locat', function(event) {
	        if ($(this).val().length >= 3) {
	          $("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + $("#event-locat").val() + '&language=en"></iframe>')
	        }else{
	          $("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=us&language=en"></iframe>')
	        }
      	});
     <?php } ?>
  jQuery(document).ready(function($) {
      $( ".date" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: 'today'});
      $( ".date1" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: '+1day'});
      $( ".time1" ).timepicker();

      $("#event-cover").change(function(event) {
        $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
      });

      $('#form-create-lead').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=lead&s=insert',
            beforeSend: function() {
              $('.wo_settings_page').find('.add_wow_loader').addClass('btn-loading');
            },
            success: function(data) {
              if (data['status'] == 200) {
                $("#lead-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
                //window.location = <?php //echo Wo_SeoLink('index.php?link1=leads'); ?>//;
                  $('.alert-success').fadeIn('fast', function () {
                      $(this).delay(2500).slideUp(500, function () {
                          $(this).remove();
                      });
                  });
                  setTimeout(function () {
                      window.location.reload();
                  }, 3000)
              }
              else if (data['message']) {
                $("#lead-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
              } 
              $('.wo_settings_page').find('.add_wow_loader').removeClass('btn-loading');
            }
      });
  });
</script>