<?php echo Wo_LoadPage('leads/includes/header'); ?>


    <!---->
    <!--    <div class="col-lg-12">-->
    <!--        <div class="wo_page_hdng_menu">-->
    <!--            <ul class="list-unstyled">-->
    <!--                <li class="--><?php //echo ($wo['active'] == "1" ? "active" : "")?><!--"><a href="--><?php //echo Wo_SeoLink('index.php?link1=leads-going'); ?><!--" data-ajax="?link1=leads-going">--><?php //echo $wo['lang']['leads_received_bids'] ?><!--</a></li>-->
    <!--                <li class="--><?php //echo ($wo['active'] == "2" ? "active" : "")?><!--"><a href="--><?php //echo Wo_SeoLink('index.php?link1=leads-going'); ?><!--" data-ajax="?link1=leads-going">--><?php //echo $wo['lang']['_leads']; ?><!--	</a></li>-->
    <!--            </ul>-->
    <!--        </div>-->
    <!--    </div>-->

    <div class="col-lg-12">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Received Bids</a></li>
        <li id="created_lead"><a data-toggle="tab" href="#menu1" >Created Leads</a></li>
    </ul>
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <!--                <h3>Received Bids</h3>-->


            <div>
                <table class="table threads-table">
                    <thead>
                    <tr>
                        <th><?php echo $wo['lang']['leads_received_bids_name']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_date']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_time']; ?> </th>
                        <th><?php echo $wo['lang']['leads_received_bids_details']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_amount']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_paynow']; ?></th>

                    </tr>
                    </thead>
                    <tbody id="mbrs">
                    </td>


                    <td><?php echo("Test") ?></td>

                    <td>
                        <span><?php echo("11/09/2010") ?></span>
                    </td>
                    <td><?php echo("2:30") ?></td>

                    <td>
                        <span>
                             <a href="<?php echo Wo_SeoLink('index.php?link1=lead-details'); ?>" data-ajax="?link1=lead-details" class="btn like-btn-text-sad"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M10,6.978c-1.666,0-3.022,1.356-3.022,3.022S8.334,13.022,10,13.022s3.022-1.356,3.022-3.022S11.666,6.978,10,6.978M10,12.267c-1.25,0-2.267-1.017-2.267-2.267c0-1.25,1.016-2.267,2.267-2.267c1.251,0,2.267,1.016,2.267,2.267C12.267,11.25,11.251,12.267,10,12.267 M18.391,9.733l-1.624-1.639C14.966,6.279,12.563,5.278,10,5.278S5.034,6.279,3.234,8.094L1.609,9.733c-0.146,0.147-0.146,0.386,0,0.533l1.625,1.639c1.8,1.815,4.203,2.816,6.766,2.816s4.966-1.001,6.767-2.816l1.624-1.639C18.536,10.119,18.536,9.881,18.391,9.733 M16.229,11.373c-1.656,1.672-3.868,2.594-6.229,2.594s-4.573-0.922-6.23-2.594L2.41,10l1.36-1.374C5.427,6.955,7.639,6.033,10,6.033s4.573,0.922,6.229,2.593L17.59,10L16.229,11.373z" ></path></svg></a>
						</span>
                    </td>
                    <td><?php echo("$200") ?></td>

                    <td>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M14.781,14.347h1.738c0.24,0,0.436-0.194,0.436-0.435v-1.739c0-0.239-0.195-0.435-0.436-0.435h-1.738c-0.239,0-0.435,0.195-0.435,0.435v1.739C14.347,14.152,14.542,14.347,14.781,14.347 M18.693,3.045H1.307c-0.48,0-0.869,0.39-0.869,0.869v12.17c0,0.479,0.389,0.869,0.869,0.869h17.387c0.479,0,0.869-0.39,0.869-0.869V3.915C19.562,3.435,19.173,3.045,18.693,3.045 M18.693,16.085H1.307V9.13h17.387V16.085z M18.693,5.653H1.307V3.915h17.387V5.653zM3.48,12.608h7.824c0.24,0,0.435-0.195,0.435-0.436c0-0.239-0.194-0.435-0.435-0.435H3.48c-0.24,0-0.435,0.195-0.435,0.435C3.045,12.413,3.24,12.608,3.48,12.608 M3.48,14.347h6.085c0.24,0,0.435-0.194,0.435-0.435s-0.195-0.435-0.435-0.435H3.48c-0.24,0-0.435,0.194-0.435,0.435S3.24,14.347,3.48,14.347"></path></svg>
                    </td>

<!--                    --><?php //echo '<tr> <td colspan="7" class="text-center" style="padding:40px 40px;" >' . $wo['lang']['leads_received_bids_nodata'] . '</td></tr>'; ?>

                    </tbody>
                </table>
            </div>
        </div>
        <div id="menu1" class="tab-pane fade">
            <!--                <h3>Created Leads</h3>-->
            <div>
                <table class="table threads-table">
                    <thead>
                    <tr>
                        <th><?php echo $wo['lang']['leads_received_bids_name']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_date']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_time']; ?> </th>
                        <th><?php echo $wo['lang']['leads_received_bids_details']; ?></th>
                        <th><?php echo $wo['lang']['leads_received_bids_amount']; ?></th>
                        <th><?php echo $wo['lang']['lead_created_bids_status']; ?></th>

                    </tr>
                    </thead>
                    <!-- created leads-->
                    <tbody id="mbrs">
                    <td><?php echo("Test") ?></td>

                    <td>
                        <span><?php echo("11/09/2010") ?></span>
                    </td>
                    <td><?php echo("2:30") ?></td>

                    <td>
                        <span>
                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M10,6.978c-1.666,0-3.022,1.356-3.022,3.022S8.334,13.022,10,13.022s3.022-1.356,3.022-3.022S11.666,6.978,10,6.978M10,12.267c-1.25,0-2.267-1.017-2.267-2.267c0-1.25,1.016-2.267,2.267-2.267c1.251,0,2.267,1.016,2.267,2.267C12.267,11.25,11.251,12.267,10,12.267 M18.391,9.733l-1.624-1.639C14.966,6.279,12.563,5.278,10,5.278S5.034,6.279,3.234,8.094L1.609,9.733c-0.146,0.147-0.146,0.386,0,0.533l1.625,1.639c1.8,1.815,4.203,2.816,6.766,2.816s4.966-1.001,6.767-2.816l1.624-1.639C18.536,10.119,18.536,9.881,18.391,9.733 M16.229,11.373c-1.656,1.672-3.868,2.594-6.229,2.594s-4.573-0.922-6.23-2.594L2.41,10l1.36-1.374C5.427,6.955,7.639,6.033,10,6.033s4.573,0.922,6.229,2.593L17.59,10L16.229,11.373z"></path></svg>
						</span>
                    </td>
                    <td><?php echo("$300") ?></td>

                    <td>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M10.219,1.688c-4.471,0-8.094,3.623-8.094,8.094s3.623,8.094,8.094,8.094s8.094-3.623,8.094-8.094S14.689,1.688,10.219,1.688 M10.219,17.022c-3.994,0-7.242-3.247-7.242-7.241c0-3.994,3.248-7.242,7.242-7.242c3.994,0,7.241,3.248,7.241,7.242C17.46,13.775,14.213,17.022,10.219,17.022 M15.099,7.03c-0.167-0.167-0.438-0.167-0.604,0.002L9.062,12.48l-2.269-2.277c-0.166-0.167-0.437-0.167-0.603,0c-0.166,0.166-0.168,0.437-0.002,0.603l2.573,2.578c0.079,0.08,0.188,0.125,0.3,0.125s0.222-0.045,0.303-0.125l5.736-5.751C15.268,7.466,15.265,7.196,15.099,7.03"></path></svg>
                    </td>

                    <!--                    --><?php //echo '<tr> <td colspan="7" class="text-center" style="padding:40px 40px;" >' . $wo['lang']['leads_received_bids_nodata'] . '</td></tr>'; ?>

                    </tbody>
                </table>
            </div>
        </div>

    </div>

    </div>
    <!--	--><?php //if (count($wo['events']) > 0): ?>
    <!--		<div id="events-going">-->
    <!--			--><?php //foreach ($wo['events'] as $wo['event']): ?>
    <!--				--><?php //echo Wo_LoadPage('leads/includes/events-list'); ?>
    <!--			--><?php //endforeach; ?>
    <!--			<div class="clear"></div>-->
    <!--		</div>-->
    <!--		<div class="row">-->
    <!--			<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">-->
    <!--			 	<div class="posts_load">-->
    <!--				    --><?php //if (count($wo['events']) > 9): ?>
    <!--					<div class="load-more">-->
    <!--	                    <button class="btn btn-default text-center pointer load-more-events" data-events-type="going">-->
    <!--	                    <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> --><?php //echo $wo['lang']['load_more'] ?><!--</button>-->
    <!--	                </div>-->
    <!--	                --><?php //endif ?>
    <!--				</div>-->
    <!--			</div>-->
    <!--		</div>-->
    <!--	--><?php //else: ?>
    <!--		--><?php //echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,12H12V17H17V12Z" /></svg>'. $wo['lang']['no_events_found'] .' </div>';?>
    <!--	--><?php //endif; ?>
<?php echo Wo_LoadPage('leads/includes/footer'); ?>


<script >
    $(document).ready(function () {
        $('#created_lead').click(function () {
            $.ajax({
                url: Wo_Ajax_Requests_File() + '?f=lead&s=get_created_leads',
// beforeSend: function() {
// $('.wo_settings_page').find('.add_wow_loader').addClass('btn-loading');
// },
                success: function(data) {
                    if (data['status'] == 200) {
                        alert("done");
                    }
                    else if (data['message']) {
                        alert('error');
                    }
                }
            });
        });
    });

</script>
