<div class="container-fluid">
    <div class="block-header">
        <h2>Users > Manage Created Leads</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Created Leads</h2>
                </div>
                <div class="body">
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Username</th>
                                <th>Service Name</th>
                                <th>Tags</th>
                                <th>Budget</th>
                                <th>Location</th>
                                <th>Manage</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach (Wo_createdlead() as $wo['createdleadlist']) {
                                echo Wo_LoadAdminPage('user-created-lead/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
<!--        <input type="hidden" id="hash_id" name="hash_id" value="--><?php //echo Wo_CreateSession();?><!--">-->
    </div>
    <!-- #END# Vertical Layout -->
