<div class="container-fluid">
    <div class="block-header">
        <h2>Users > Manage Created Leads</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Created Leads</h2>
                </div>
                <div class="body">
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Username</th>
                                <th>Service Name</th>
                                <th>Tags</th>
                                <th>Budget</th>
                                <th>Location</th>
                                <th>Manage</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach (Wo_createdlead() as $wo['createdleadlist']) {
                                echo Wo_LoadAdminPage('user-created-lead/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="modal fade" id="editcategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal_content_back">
            <div class="modal-header">
                <h5 class="modal-title" id="editcategoryModalLabel">Edit Lead</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="edit_category_form_alert"></div>
                <form class="edit_category_lang" method="POST" id="modal-body-langs">
                    <div class="data_lang">
                        <input class="form-control" type="hidden" id="id" name="id" value="">
                        <label>Service Name</label>
                        <input class="form-control" type="text"id="name" name="name"  value="">
                        <label>Tags</label>
                        <input class="form-control" type="text"id="tags" name="tags" value="">
                        <label>Budget</label>
                     <input class="form-control" type="text" id="budget" name="budget"  value="">
                     <label>Location</label>
                     <input class="form-control" type="text" id="location" name="location"  value="">

                    <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    <input type="hidden" name="id_of_key" id="id_of_key" value="">
                    </div>
                </form>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal">CLOSE</button>
                <button type="button" class="btn btn-primary" id="save_edited_category" onclick="update_lead()">SAVE CHANGES</button>
            </div>
        </div>
    </div>
</div>

                </div>
            </div>
        </div>
        <div class="clearfix"></div>
<!--        <input type="hidden" id="hash_id" name="hash_id" value="--><?php //echo Wo_CreateSession();?><!--">-->
    </div>
    <!-- #END# Vertical Layout -->

    <script>
        function open_edit_currency(lead_id) {
            $('#defaultModal').modal('show');
            $('#lead_id').val(lead_id);
            $('#users').val(users);
        }
        function Wo_Deletelead(lead_id) {
            if (confirm("Are you sure you want to delete this Lead?") == false) {
                return false;
            }
            hash_id = $('#hash_id').val();
            $('#UserID_' + lead_id).fadeOut(300, function() {
                $(this).remove();
            });
            $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'delete_created_lead', lead_id: lead_id, hash_id: hash_id});
        }
        function edit_lead(id) {
        $('#id_of_key').val(id);
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=edit_lead', {lead_id: id}, function(data, textStatus, xhr) {
            if (data.status == 200) {
                // $('.data_lang').html(data.package);
                $('#id').val(data.package['id']);
                $('#name').val(data.package['service_name']);
                $('#tags').val(data.package['tag_keyword']);
                $('#budget').val(data.package['budget']);
                $('#location').val(data.package['service_location']);
                $('#editcategoryModal').modal();
            }
        });
    }
        function Wo_SubmitCurrencyForm() {
            $('.edit-curreny-settings').submit();
        }
        var form_edit_site_settings = $('form.edit-curreny-settings');
        form_edit_site_settings.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=send-lead&s=send-created-lead',
            beforeSend: function() {
                form_edit_site_settings.find('.waves-effect').text('Please wait..');
            },
            success: function(data) {
                if (data.status == 200) {
                    form_edit_site_settings.find('.waves-effect').text('SAVE CHANGES');
                    $("html, body").animate({ scrollTop: 0 }, "slow");
                    $('.edit-curreny-settings-alert').html('<i class="fa fa-check"></i> Lead successfully sent');
                    setTimeout(function () {
                        $('.edit-curreny-settings-alert').empty();
                        location.reload();
                    }, 2000);
                }
                else {
                    alert("no response");
                }
            }
        });

        function update_lead() {
        let lead_id=$('#id').val();
        let service_name=$('#name').val();
        let tags=$('#tags').val();
        let budget=$('#budget').val();
        let s_location=$('#location').val();

        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_lead',
        {lead_id: lead_id,service_name:service_name,tags:tags,budget:budget,location:s_location},
         function(data, textStatus, xhr) {
            setTimeout(function(){// wait for 5 secs(2)
            location.reload(); // then reload the page.(3)
      }, 500);
        });
    }
    </script>

    <div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content ">
                <div class="modal-header">
                    <h4 class="modal-title" id="defaultModalLabel">Send Lead</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-success edit-curreny-settings-alert"></div>
                    <form class="edit-curreny-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <select name="user[]" id="users" class="select-2 form-control" multiple>
                                    <?php
                                    $getuser=getusers_send_lead();
                                    foreach ($getuser as $wo['get_user']) {
                                        echo '<option value="'.$wo['get_user']['user_id'].'">'.$wo['get_user']['username'].'</option>';
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br><br>
                        <input type="hidden" name="lead_id" id="lead_id">
<!--                        <input type="hidden" name="hash_id" value="--><?php //echo Wo_CreateSession();?><!--">-->
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" onclick="Wo_SubmitCurrencyForm();" class="btn-save btn btn-link waves-effect">SAVE CHANGES</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
                </div>
            </div>
        </div>
    </div>
