<tr class="user-list" id="UserID_<?php echo $wo['createdleadlist']['id']?>"
    data-user-id="<?php echo $wo['createdleadlist']['id']?>">
    <td><?php echo $wo['createdleadlist']['user_id']?></td>
    <td><?php echo $wo['createdleadlist']['username']?></td>
    <td><?php echo $wo['createdleadlist']['service_name']?></td>
    <td><?php echo $wo['createdleadlist']['tag_keyword']?></td>
    <td><?php echo $wo['createdleadlist']['budget']?></td>
    <td><?php echo $wo['createdleadlist']['service_location']?></td>
    <td>
        <div class="dropdown" style="display: inline;">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-sliders dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>
            <ul class="dropdown-menu dropdown-menu-right" role="menu" style="min-width: 80px; font-size: 12px;">
                <li>
                <a href="javascript:void(0)" onclick="open_edit_currency('<?php echo $wo['createdleadlist']['id']; ?>')" >Send Lead</a>
                </li>
                 <li>
                    <a href="javascript:void(0)" onclick="Wo_Deletelead(<?php echo $wo['createdleadlist']['id']?>);">Delete</a>
                </li>
                <li>
                <a href="javascript:void(0)" class=" waves-effect waves-light" onclick="edit_lead(<?php echo $wo['createdleadlist']['id']?>);">
                                            Edit
                                        </a>
                                        </li>
            </ul>
        </div>
    </td>
</tr>