<div class="container-fluid">
    <div class="block-header">
        <h2>Normal Leads >  Create New Normal Leads</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="header">
                    <h2>Create New Normal Leads</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success newforum-alert"></div>
                    <div class="alert alert-danger newforum-error-alert"></div>
                    <form class="newforum" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="name" name="name" class="form-control">
                                <label class="form-label">Serivce Name</label>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="tag" name="tag" class="form-control">
                                <label class="form-label">Tags</label>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="lead-location" name="service_location" class="form-control">
                                <label class="form-label" for="lead-locat">Serivce Location</label>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="budget" name="budget" class="form-control">
                                <label class="form-label">Budget</label>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="detail" name="detail" class="form-control">
                                <label class="form-label">Details</label>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <br><br>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Create</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
    <script>

        $(function() {
            var form_new_forum = $('form.newforum');
            form_new_forum.ajaxForm({
                url: Wo_Ajax_Requests_File()  +  '?f=add_new_normal_lead&hash=' + $('.main_session').val(),
                beforeSend: function() {
                    form_new_forum.find('.waves-effect').text('Please wait..');
                },
                success: function(data) {
                    if (data.status == 200) {
                        $("html, body").animate({ scrollTop: 0 }, "slow");
                        $('.newforum-alert').html('<i class="fa fa-check"></i> Lead successfully added');
                        $('.newforum-error-alert').empty();
                    } else {
                        $('.newforum-alert').empty();
                        $(".newforum-error-alert").html(data['message']);
                    }
                    form_new_forum.find('.waves-effect').text('Create');
                }
            });
        });
    </script>