<?php
$show_list = false;
if (!Wo_IsPrivateGroupOnwer($wo['group_profile']['id'])) {
	if (($wo['group_profile']['id'])) {
		$show_list = true;
	}
} else {
	$show_list = true;
}
?>
<div class="row page-margin wo_group_profile" data-page="private_group" data-id="<?php echo $wo['group_profile']['id']; ?>">
	<div class="profile-container">
		<div class="card hovercard">
			<div class="cardheader user-cover">
				<?php if (Wo_IsPrivateGroupOnwer($wo['group_profile']['id']) === true) { ?>
					<form action="#" method="post" class="profile-cover-changer">
						<div class="input-group">
							<span class="input-group-btn profile_cover">
								<span class="btn btn-upload-image btn-file">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-camera">
										<path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
										<circle cx="12" cy="13" r="4"></circle>
									</svg>
									<input type="file" name="cover" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileCover();">
								</span>
							</span>
						</div>
						<input type="hidden" name="group_id" id="group-id" value="<?php echo $wo['group_profile']['id']; ?>">
					</form>
				<?php } ?>
				<div class="user-cover-uploading-container"></div>
				<div class="user-cover-uploading-progress">
					<div class="pace-activity-parent">
						<div class="pace-activity"></div>
					</div>
				</div>
				<img id="cover-image" src="<?php echo $wo['group_profile']['cover'] ?>" alt="<?php echo $wo['group_profile']['name'] ?> Cover Image" />
			</div>

			<div class="side_panel">
				<div class="box-inner" style="background-image: url(<?php echo $wo['group_profile']['cover'] ?>)"></div>
				<div class="sp_innrr">
					<div class="user-avatar flip">
						<div class="user-avatar-uploading-container">
							<div class="user-avatar-uploading-progress">
								<div class="ball-pulse">
									<div></div>
									<div></div>
									<div></div>
								</div>
							</div>
						</div>
						<img id="group-avatar-image" alt="<?php echo $wo['group_profile']['name'] ?> Profile Picture" src="<?php echo $wo['group_profile']['avatar'] ?>" />
						<?php if (Wo_IsPrivateGroupOnwer($wo['group_profile']['id']) === true) { ?>
							<form action="#" method="post" class="profile-avatar-changer">
								<div class="input-group profile_avatar">
									<span class="input-group-btn">
										<span class="btn btn-upload-image btn-file">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-camera">
												<path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
												<circle cx="12" cy="13" r="4"></circle>
											</svg>
											<input type="file" name="avatar" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileAvatar();">
										</span>
									</span>
								</div>
								<input type="hidden" name="group_id" id="group-id" value="<?php echo $wo['group_profile']['id']; ?>">
							</form>
						<?php } ?>
					</div>
					<div class="info">
						<div class="title">
							<a href="<?php echo Wo_SeoLink('index.php?link1=?link1=timeline&u=' . $wo['group_profile']['group_name'] . ''); ?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name']; ?>">
								<?php echo $wo['group_profile']['name']; ?>
							</a>
						</div>
						<span style="display: block;"><?php echo Wo_CountPrivateGroupMembers($wo['group_profile']['id']); ?> <?php echo $wo['lang']['members']; ?></span>
					</div>
					<div class="options-buttons">
						<span class="user-follow-button group-join-btn">
							<?php echo Wo_GetPrivateJoinButton($wo['group_profile']['id']); ?>
						</span>
						<?php if (Wo_IsPrivateGroupOnwer($wo['group_profile']['id'])) { ?>
							<a href="<?php echo Wo_SeoLink('index.php?link1=private-group-setting&group=' .  $wo['group_profile']['group_name']); ?>" data-ajax="?link1=private-group-setting&group=<?php echo $wo['group_profile']['group_name']; ?>" class="btn btn-default"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2">
									<polygon points="16 3 21 8 8 21 3 21 3 16 16 3"></polygon>
								</svg> <?php echo $wo['lang']['edit']; ?></a>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-8">
		<?php
		if (isset($_GET['type'])) {
			if ($_GET['type'] == 'members') {
				if ($show_list == true) {
					# code...
		?>

					<div class="list-group profile-lists">
						<div class="list-group-item">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users">
								<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
								<circle cx="9" cy="7" r="4"></circle>
								<path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
								<path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
							</svg>
<?php echo $wo['lang']['members']; ?>
</div>
<!--<div class="page-margin wow_content mt-0">-->
<!--<div class="wo_page_hdng pag_neg_padd pag_alone">-->
<!--<div class="wo_page_hdng_innr">-->
<!--    <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">-->
<!--            <path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path>-->
<!--        </svg></span> <?php echo $wo['lang']['members']; ?>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="list-group profile-lists">-->
						<div class="row" style="margin: 0;">
							<?php
							if (Wo_CountPrivateGroupMembers($wo['group_profile']['id']) == 0) {
								echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>' . $wo['lang']['no_members_found'] . '</h5>';
							} else {
								foreach (Wo_GetPrivateGroupMembers($wo['group_profile']['id']) as $wo['UsersList']) {
									$wo['group_member'] = true;
									echo Wo_LoadPage('timeline/follow-list');
								}
							}
							?>
						</div>
						<div class="clear"></div>
<!--					</div>-->
				<?php }
			} else if ($_GET['type'] == 'invite_members') { ?>

			<!--private group-->
			<div class="list-group profile-lists">
					<div class="list-group-item">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-plus">
							<path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
							<circle cx="8.5" cy="7" r="4"></circle>
							<line x1="20" y1="8" x2="20" y2="14"></line>
							<line x1="23" y1="11" x2="17" y2="11"></line>
						</svg>
<?php echo $wo['lang']['invite_your_friends']; ?>
</div>
<div class="row" style="margin: 0;">
<?php
if (Wo_CountPrivateGroupsNotMember($wo['group_profile']['id']) == 0) {
    echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-plus"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><line x1="20" y1="8" x2="20" y2="14"></line><line x1="23" y1="11" x2="17" y2="11"></line></svg>' . $wo['lang']['invited_all_friends'] . '</h5>';
} else {
							foreach (Wo_GetPrivateGroupsNotMember($wo['group_profile']['id']) as $wo['UsersList']) {
								$wo['group_invited'] = Wo_isUserInvited($wo['UsersList']['user_id'], $wo['group_profile']['id']);
								echo Wo_LoadPage('private_group/add-list');
							}
						}
						?>
</div>
<div class="clear"></div>
</div>

<!--private lead-->
<div class="list-group profile-lists">
<div class="wo_page_hdng pag_neg_padd pag_alone">
<div class="wo_page_hdng_innr">
    <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
            <path fill="currentColor" d="M13,13C11,13 7,14 7,16V18H19V16C19,14 15,13 13,13M19.62,13.16C20.45,13.88 21,14.82 21,16V18H24V16C24,14.46 21.63,13.5 19.62,13.16M13,11A3,3 0 0,0 16,8A3,3 0 0,0 13,5A3,3 0 0,0 10,8A3,3 0 0,0 13,11M18,11A3,3 0 0,0 21,8A3,3 0 0,0 18,5C17.68,5 17.37,5.05 17.08,5.14C17.65,5.95 18,6.94 18,8C18,9.06 17.65,10.04 17.08,10.85C17.37,10.95 17.68,11 18,11M8,10H5V7H3V10H0V12H3V15H5V12H8V10Z"></path>
        </svg></span> <?php echo $wo['lang']['invite_your_friends']; ?>
						</div>
					</div>
				</div>
				<div class="list-group profile-lists">
					<div class="row" style="margin: 0;">
						<?php
						if (Wo_CountPrivateGroupsNotMember($wo['group_profile']['id']) == 0) {
							echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-plus"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><line x1="20" y1="8" x2="20" y2="14"></line><line x1="23" y1="11" x2="17" y2="11"></line></svg>' . $wo['lang']['invited_all_friends'] . '</h5>';
						} else {
							foreach (Wo_GetPrivateGroupsNotMember($wo['group_profile']['id']) as $wo['UsersList']) {
								$wo['group_invited'] = Wo_isUserInvited($wo['UsersList']['user_id'], $wo['group_profile']['id']);
								echo Wo_LoadPage('private_group/add-list');
							}
						}
						?>
					</div>
					<div class="clear"></div>
				</div>
			<?php } else if ($_GET['type'] == 'referrals') { ?>
				<div class="page-margin wow_content mt-0">
					<div class="wo_page_hdng pag_neg_padd pag_alone">
						<div class="wo_page_hdng_innr justify-content-between">
							<div>
								<span>
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
										<path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
									</svg>
								</span>

								<?php echo $wo['lang']['referrals']; ?>
							</div>

							<div>
								<a id="send-referral" class="btn btn-main" href="">
									<?php echo $wo['lang']['send_referral']; ?>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="list-group profile-lists">
					<div class="row" style="margin: 0;">
						<?php
						if (Wo_CountPrivateData() == 0) {
							echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-plus"><path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path></svg>' . $wo['lang']['no_referrals_found'] . '</h5>';
						} else {
							foreach (Wo_GetPrivateData() as $wo['ReferralList']) {
								echo Wo_LoadPage('private_group/referral-list');
							}
						}
						?>
					</div>

					<div class="clear"></div>
				</div>
			<?php } else if ($_GET['type'] == 'thanks') { ?>
				<div class="page-margin wow_content mt-0">
					<div class="wo_page_hdng pag_neg_padd pag_alone">
						<div class="wo_page_hdng_innr justify-content-between">
							<div>
								<span>
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
										<path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
									</svg>
								</span>

								<?php echo $wo['lang']['thanks']; ?>
							</div>

							<div>
								<?php if (Wo_CanSendThanks() == true) { ?>
									<a id="send-thanks" class="btn btn-main" href=""><?php echo $wo['lang']['send_thanks']; ?></a>
								<?php } ?>
							</div>
						</div>
					</div>
				</div>

				<div class="list-group profile-lists">
					<div class="row" style="margin: 0;">
						<?php
						if (Wo_CountPrivateData('thanks') == 0) {
							echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-plus"><path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path></svg>' . $wo['lang']['no_thanks_found'] . '</h5>';
						} else {
							foreach (Wo_GetPrivateData('thanks') as $wo['ThanksList']) {
								echo Wo_LoadPage('private_group/thanks-list');
							}
						}
						?>
					</div>

					<div class="clear"></div>
				</div>
			<?php }
		} else { ?>
			<?php echo Wo_GetPrivateGroupPostPublisherBox($wo['group_profile']['id']); ?>
			<?php if ($wo['loggedin'] == true) {
				echo Wo_LoadPage('story/filter-by');
			} ?>

			<div id="posts" data-story-private="<?php echo $wo['group_profile']['id']; ?>">
				<div class="pinned-post-container">
					<?php
					$pinedstory = Wo_GetPinnedPost($wo['group_profile']['id'], 'private_group');
					if (count($pinedstory) == 1) {
						foreach ($pinedstory  as $wo['story']) {
							echo Wo_LoadPage('story/content');
						}
					}
					?>
				</div>
				<?php
				$stories = Wo_GetPosts(array('filter_by' => 'all', 'private_id' => $wo['group_profile']['id'], 'placement' => 'multi_image_post', 'custom' => true));
				if (count($stories) == 0 && count($pinedstory) == 0) {
					echo Wo_LoadPage('story/group-no-stories');
				} else {
					foreach ($stories as $wo['story']) {
						echo Wo_LoadPage('story/content');
					}
				}
				?>
			</div>
			<?php if ($wo['loggedin'] == true && count($stories) > 0) {  ?>
				<div class="load-more pointer" id="load-more-posts" onclick="Wo_GetMorePosts();">
					<span class="btn btn-default"><i class="fa fa-chevron-circle-down progress-icon" data-icon="chevron-circle-down"></i> &nbsp;<?php echo $wo['lang']['load_more_posts']; ?><span>
				</div>
		<?php }
		} ?>
		<div id="load-more-filter">
			<span class="filter-by-more hidden" data-filter-by="all"></span>
		</div>
	</div>

	<div class="col-md-4">
		<?php if ($wo['loggedin'] == true) {  ?>
			<div class="wow_content">
				<div class="wow_form_fields mt-0">
					<label class="mt-0" for="invite_your_frineds"><?php echo $wo['lang']['search_for_posts']; ?></label>
					<input type="text" class="search-for-posts" onkeyup="Wo_SearchForPosts(this.value);" />
				</div>
			</div>
		<?php } ?>
		<ul class="page-margin wow_content negg_padd list-unstyled event-options-list right_user_info">
			<div class="wo_page_hdng">
				<div class="wo_page_hdng_innr">
					<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
							<path fill="currentColor" d="M13,9H11V7H13M13,17H11V11H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
						</svg></span> <?php echo $wo['lang']['info']; ?>
				</div>
			</div>
			<?php
			$group_privacy = $wo['lang']['private'];
			$group_icon = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17A2,2 0 0,0 14,15C14,13.89 13.1,13 12,13A2,2 0 0,0 10,15A2,2 0 0,0 12,17M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V10C4,8.89 4.9,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z"></path></svg>';
			?>

			<?php if ($show_list == true) : ?>
				<li class="list-group-item">
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
						<path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path>
					</svg>
					<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=members'); ?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name']; ?>&type=members"><?php echo Wo_CountPrivateGroupMembers($wo['group_profile']['id']); ?> <?php echo $wo['lang']['members']; ?></a>
					<?php if (Wo_IsPrivateGroupOnwer($wo['group_profile']['id'])) { ?>
						<span class="green">+<?php echo Wo_CountPrivateJoinedThisWeek($wo['group_profile']['id']); ?> <?php echo $wo['lang']['this_week']; ?></span>
					<?php } ?>
				</li>
			<?php endif ?>
			<li>
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
					<path fill="currentColor" d="M19 5V19H5V5H19M21 3H3V21H21V3M17 17H7V16H17V17M17 15H7V14H17V15M17 12H7V7H17V12Z"></path>
				</svg> <?php echo Wo_CountPrivateGroupPosts($wo['group_profile']['id']); ?> <?php echo $wo['lang']['posts']; ?>
			</li>
			<?php if ($wo['loggedin'] == true) { ?>
				<?php if (Wo_IsPrivateGroupJoined($wo['group_profile']['id']) === true && Wo_PrivateCanInvite($wo['group_profile']['id']) == true) { ?>
					<li>
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<path fill="currentColor" d="M13,13C11,13 7,14 7,16V18H19V16C19,14 15,13 13,13M19.62,13.16C20.45,13.88 21,14.82 21,16V18H24V16C24,14.46 21.63,13.5 19.62,13.16M13,11A3,3 0 0,0 16,8A3,3 0 0,0 13,5A3,3 0 0,0 10,8A3,3 0 0,0 13,11M18,11A3,3 0 0,0 21,8A3,3 0 0,0 18,5C17.68,5 17.37,5.05 17.08,5.14C17.65,5.95 18,6.94 18,8C18,9.06 17.65,10.04 17.08,10.85C17.37,10.95 17.68,11 18,11M8,10H5V7H3V10H0V12H3V15H5V12H8V10Z"></path>
						</svg>
						<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=invite_members'); ?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name']; ?>&type=invite_members"><?php echo $wo['lang']['invite_your_friends']; ?></a>
					</li>
				<?php } ?>

				<?php if ($wo['group_profile']['active']) { ?>
					<li>
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
						</svg>
						<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=referrals'); ?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name']; ?>&type=referrals"><?php echo $wo['lang']['referrals']; ?></a>
					</li>

					<li>
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
						</svg>

						<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=thanks'); ?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name']; ?>&type=thanks"><?php echo $wo['lang']['thanks']; ?></a>
					</li>
				<?php } ?>
			<?php } ?>

			<?php if ($wo['loggedin'] && !Wo_IsAdmin() && $wo['user']['id'] != $wo['group_profile']['user_id'] && !Wo_IsAdmin($wo['group_profile']['user_id'])) : ?>
				<?php if (!Wo_IsReportExists($wo['group_profile']['id'], 'private_group')) : ?>
					<li id="report_status" class="pointer" onclick="$('#report_group').modal('show');">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle">
							<path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
							<line x1="12" y1="9" x2="12" y2="13"></line>
							<line x1="12" y1="17" x2="12" y2="17"></line>
						</svg>
						<span><?php echo $wo['lang']['report_group']; ?></span>
					</li>
				<?php else : ?>
					<li id="report_status" class="pointer" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,false);">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle">
							<path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
							<line x1="12" y1="9" x2="12" y2="13"></line>
							<line x1="12" y1="17" x2="12" y2="17"></line>
						</svg>
						<span><?php echo $wo['lang']['unreport']; ?></span>
					</li>
				<?php endif; ?>
			<?php endif; ?>
		</ul>

		<?php if (!empty($wo['group_profile']['about'])) {  ?>
			<div class="page-margin wow_content">
				<div class="wo_page_hdng pag_neg_padd">
					<div class="wo_page_hdng_innr">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
								<path fill="currentColor" d="M21,6V8H3V6H21M3,18H12V16H3V18M3,13H21V11H3V13Z"></path>
							</svg></span> <?php echo $wo['lang']['about']; ?>
					</div>
				</div>
				<p class="page-margin"><?php echo $wo['group_profile']['about'] ?></p>
			</div>
		<?php } ?>

		<?php
		$sidebar_ad = Wo_GetAd('sidebar', false);
		if (!empty($sidebar_ad)) { ?>
			<ul class="list-group sidebar-ad">
				<?php echo $sidebar_ad; ?>
			</ul>
		<?php } ?>
		<?php echo Wo_LoadPage('footer/sidebar-footer') ?>
	</div>
</div>

<div class="modal fade" id="report_group" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
							<line x1="18" y1="6" x2="6" y2="18"></line>
							<line x1="6" y1="6" x2="18" y2="18"></line>
						</svg></span></button>
				<h4 class="modal-title">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle">
						<path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
						<line x1="12" y1="9" x2="12" y2="13"></line>
						<line x1="12" y1="17" x2="12" y2="17"></line>
					</svg>
					<?php echo $wo['lang']['report_group']; ?>
				</h4>
			</div>
			<div class="modal-body">
				<textarea class="form-control" placeholder="Type text" dir="auto" rows="4" id="report-group-text-<?php echo $wo['group_profile']['id']; ?>"></textarea>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse">
					<div></div>
					<div></div>
					<div></div>
				</div>
				<button type="button" class="btn  btn-main" id="report-group-button" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,true)">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right">
						<line x1="5" y1="12" x2="19" y2="12"></line>
						<polyline points="12 5 19 12 12 19"></polyline>
					</svg>
					<?php echo $wo['lang']['send']; ?>
				</button>
			</div>
		</div>
	</div>
</div>

<?php if ($wo['group_profile']['active']) { ?>
	<div class="modal fade" id="send_referral_modal" role="dialog">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
								<line x1="18" y1="6" x2="6" y2="18"></line>
								<line x1="6" y1="6" x2="18" y2="18"></line>
							</svg></span></button>
					<h4 class="modal-title">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-send">
							<path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
							<line x1="12" y1="9" x2="12" y2="13"></line>
							<line x1="12" y1="17" x2="12" y2="17"></line>
						</svg>
						<?php echo $wo['lang']['special_referral']; ?>
					</h4>
				</div>
				<form class="send_referral_form" data-type="referral" method="post">
					<div class="modal-body">
						<div class="blog-alert"></div>

						<div class="wow_form_fields">
							<input id="referral_to" onkeyup="searchUser(this, 'referral')" name="referral_to" type="text" placeholder="<?php echo $wo['lang']['to']; ?>" autocomplete="off">

							<div class="search-result">
								<ul class="search-list"></ul>
							</div>
						</div>

						<label for="referral_type"><?php echo $wo['lang']['referral_type']; ?></label>
						<div class="switch-field">
							<input type="radio" name="referral_type" id="type-inside" value="inside" checked>
							<label for="type-inside"><?php echo $wo['lang']['inside']; ?></label>
							<input type="radio" name="referral_type" id="type-outside" value="outside">
							<label for="type-outside" class="m-l-20"><?php echo $wo['lang']['outside']; ?></label>
						</div>
						<div class="wow_form_fields mb-0">
							<label for="referral_status"><?php echo $wo['lang']['referral_status']; ?></label>
						</div>
						<div class="row">
							<div class="col-xs-1 col-md-1"></div>
							<div class="col-xs-11 col-md-11 row">
								<div class="col-xs-12 col-md-12 round-check">
									<input type="checkbox" id="call" name="call" value="call">
									<label for="call"><?php echo $wo['lang']['referral_status_call'] ?></label>
								</div>
								<div class="col-xs-12 col-md-12 round-check">
									<input type="checkbox" id="card" name="card" value="card">
									<label for="card"><?php echo $wo['lang']['referral_status_card'] ?></label>
								</div>
							</div>
						</div>

						<div class="wow_form_fields">
							<input id="referral" name="referral" type="text" placeholder="<?php echo $wo['lang']['referral'] ?>">
						</div>

						<div class="wow_form_fields">
							<input id="telephone" name="telephone" type="tel" placeholder="<?php echo $wo['lang']['phone_num_ex'] ?>">
						</div>

						<div class="wow_form_fields">
							<input id="email" name="email" type="email" placeholder="<?php echo $wo['lang']['email_address'] ?>">
						</div>

						<div class="wow_form_fields">
							<input id="address" name="address" type="text" placeholder="<?php echo $wo['lang']['address'] ?>">
						</div>

						<div class="wow_form_fields">
							<input id="comments" name="comments" type="text" placeholder="<?php echo $wo['lang']['comments'] ?>">
						</div>

						<div class="graph-row">
							<div class="round-check">
								<label class="d-block" for="cold">
									<img src="<?php echo $wo['config']['site_url'] ?>/upload/photos/cold.png">
								</label>
								<input type="radio" id="cold" name="graph_level" value="cold" checked>
							</div>
							<div class="round-check">
								<label class="d-block" for="heat">
									<img src="<?php echo $wo['config']['site_url'] ?>/upload/photos/heat.png">
								</label>
								<input type="radio" id="heat" name="graph_level" value="heat">
							</div>
							<div class="round-check">
								<label class="d-block" for="warm">
									<img src="<?php echo $wo['config']['site_url'] ?>/upload/photos/warm.png">
								</label>
								<input type="radio" id="warm" name="graph_level" value="warm">
							</div>
							<div class="round-check">
								<label class="d-block" for="hot">
									<img src="<?php echo $wo['config']['site_url'] ?>/upload/photos/hot.png">
								</label>
								<input type="radio" id="hot" name="graph_level" value="hot">
							</div>
						</div>

						<input type="hidden" id="user_id" name="user_id" value="0">
						<input type="reset" id="referral-reset" value="Reset" class="hidden">
					</div>
					<div class="modal-footer">
						<div class="ball-pulse">
							<div></div>
							<div></div>
							<div></div>
						</div>
						<button type="submit" class="btn btn-main">
							<?php echo $wo['lang']['send']; ?>
						</button>
					</div>
				</form>

			</div>
		</div>
	</div>

	<?php if (Wo_CanSeeReferral() == true) { ?>
		<?php $wo['referral_data'] = Wo_GetReferral(); ?>
		<?php $wo['sender_data'] = Wo_UserData($wo['referral_data']['sender_id']); ?>
		<div class="modal fade" id="referral_modal" role="dialog">
			<div class="modal-dialog modal-sm">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
									<line x1="18" y1="6" x2="6" y2="18"></line>
									<line x1="6" y1="6" x2="18" y2="18"></line>
								</svg></span></button>
						<h4 class="modal-title">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-send">
								<path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
								<line x1="12" y1="9" x2="12" y2="13"></line>
								<line x1="12" y1="17" x2="12" y2="17"></line>
							</svg>
							<?php echo $wo['lang']['referral_notice']; ?>
						</h4>
					</div>
					<div class="modal-body">
						<div class="blog-alert"></div>

						<div class="table-responsive1">
							<table class="table table-bordered">
								<tbody>
									<tr>
										<td>Sent By</td>
										<td>
											<img src="<?php echo $wo['sender_data']['avatar']; ?>" class="setting-avatar" alt="<?php echo $wo['sender_data']['avatar'] ?> Profile Picture">
											<?php echo $wo['sender_data']['name']; ?>
										</td>
									</tr>

									<tr>
										<td>Referral</td>
										<td>
											<?php echo $wo['referral_data']['referral']; ?>
										</td>
									</tr>

									<tr>
										<td>Referral Type</td>
										<td>
											<?php echo ucfirst($wo['referral_data']['referral_type']); ?>
										</td>
									</tr>

									<?php if ($wo['referral_data']['call'] == 1 || $wo['referral_data']['card'] == 1) { ?>

										<?php if ($wo['referral_data']['call'] == 1) { ?>
											<tr>
												<td>Referral Status</td>
												<td>
													Told them you would call
												</td>
											</tr>
										<?php } ?>

										<?php if ($wo['referral_data']['card'] == 1) { ?>
											<tr>
												<td><?php echo ($wo['referral_data']['call'] == 0) ? 'Referral Status' : '' ?></td>
												<td>
													Given your card
												</td>
											</tr>
										<?php } ?>
									<?php } ?>

									<tr>
										<td>Temperature Level</td>
										<td>
											<?php echo ucfirst($wo['referral_data']['graph_level']); ?>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>

					<input type="hidden" id="referral_id" value="<?php echo $wo['referral_data']['id'] ?>">
					<div class="modal-footer">
						<div class="ball-pulse">
							<div></div>
							<div></div>
							<div></div>
						</div>
						<button class="btn btn-main" onclick="Wo_changeReferralStatus(this, 'accept')">
							<?php echo $wo['lang']['accept']; ?>
						</button>
						<button class="btn btn-main" onclick="Wo_changeReferralStatus(this, 'reject')">
							<?php echo $wo['lang']['reject']; ?>
						</button>
					</div>
				</div>
			</div>
		</div>

		<div class="modal fade" id="send_forward_modal" role="dialog">
			<div class="modal-dialog modal-sm">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
									<line x1="18" y1="6" x2="6" y2="18"></line>
									<line x1="6" y1="6" x2="18" y2="18"></line>
								</svg></span></button>
						<h4 class="modal-title">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-send">
								<path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
								<line x1="12" y1="9" x2="12" y2="13"></line>
								<line x1="12" y1="17" x2="12" y2="17"></line>
							</svg>
							<?php echo $wo['lang']['resend_referral']; ?>
						</h4>
					</div>
					<form class="send_forward_form" data-type="forward" method="post">
						<div class="modal-body">
							<div class="blog-alert"></div>
							<div class="wow_form_fields">
								<label><?php echo $wo['lang']['send_resend_referral']; ?></label>
							</div>

							<div class="wow_form_fields">
								<input id="forward_to" onkeyup="searchUser(this, 'forward')" name="forward_to" type="text" placeholder="<?php echo $wo['lang']['activation_resend'] . ' ' . $wo['lang']['to']; ?>" autocomplete="off">

								<div class="search-result">
									<ul class="search-list"></ul>
								</div>
							</div>

							<input type="hidden" id="user_id" name="user_id" value="0">
							<input type="hidden" name="referral_id" value="<?php echo $wo['referral_data']['id'] ?>">
							<input type="reset" id="forward-reset" value="Reset" class="hidden">
						</div>
						<div class="modal-footer">
							<div class="ball-pulse">
								<div></div>
								<div></div>
								<div></div>
							</div>
							<button type="submit" class="btn btn-main">
								<?php echo $wo['lang']['send']; ?>
							</button>

							<button type="button" class="btn btn-main" data-dismiss="modal">
								<?php echo $wo['lang']['cancel']; ?>
							</button>
						</div>
					</form>

				</div>
			</div>
		</div>
	<?php } ?>

	<div class="modal fade" id="send_thanks_modal" role="dialog">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
								<line x1="18" y1="6" x2="6" y2="18"></line>
								<line x1="6" y1="6" x2="18" y2="18"></line>
							</svg></span></button>
					<h4 class="modal-title">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-send">
							<path fill="currentColor" d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
							<line x1="12" y1="9" x2="12" y2="13"></line>
							<line x1="12" y1="17" x2="12" y2="17"></line>
						</svg>
						<?php echo $wo['lang']['send_thanks']; ?>
					</h4>
				</div>
				<form class="send_thanks_form" data-type="thanks" method="post">
					<div class="modal-body">
						<div class="blog-alert"></div>

						<div class="wow_form_fields">
							<input id="thanks_to" onkeyup="searchUser(this, 'thanks')" name="thanks_to" type="text" placeholder="<?php echo $wo['lang']['to']; ?>" autocomplete="off">

							<div class="search-result">
								<ul class="search-list"></ul>
							</div>
						</div>

						<div class="wow_form_fields">
							<input id="appreciation_value" name="appreciation_value" type="text" placeholder="<?php echo $wo['lang']['appreciation_value']; ?>" autocomplete="off">
						</div>

						<label for="thanks_type"><?php echo $wo['lang']['type']; ?></label>
						<div class="switch-field">
							<input type="radio" name="thanks_type" id="type-new" value="new" checked>
							<label for="type-new"><?php echo $wo['lang']['new']; ?></label>
							<input type="radio" name="thanks_type" id="type-repeat" value="repeat">
							<label for="type-repeat" class="m-l-20"><?php echo $wo['lang']['repeat']; ?></label>
						</div>

						<label for="referral_type"><?php echo $wo['lang']['referral_type']; ?></label>
						<div class="switch-field">
							<input type="radio" name="referral_type" id="type-inside" value="inside" checked>
							<label for="type-inside"><?php echo $wo['lang']['inside']; ?></label>
							<input type="radio" name="referral_type" id="type-outside" value="outside">
							<label for="type-outside" class="m-l-20"><?php echo $wo['lang']['outside']; ?></label>
						</div>

						<div class="wow_form_fields mb-0">
							<textarea id="comments" name="comments" type="text" rows="3" placeholder="<?php echo $wo['lang']['comments'] ?>"></textarea>
						</div>

						<input type="hidden" id="user_id" name="user_id" value="0">
						<input type="reset" id="thanks-reset" value="Reset" class="hidden">
					</div>
					<div class="modal-footer">
						<div class="ball-pulse">
							<div></div>
							<div></div>
							<div></div>
						</div>
						<button type="submit" class="btn btn-main">
							<?php echo $wo['lang']['send']; ?>
						</button>
					</div>
				</form>

			</div>
		</div>
	</div>
<?php } ?>

<!-- JS Pages functions -->
<script>
	<?php if ($wo['group_profile']['active']) { ?>

		function Wo_SendInvite(user_id, group_id) {
			Wo_progressIconLoader($('#add-' + user_id).find('button'));
			$.get(Wo_Ajax_Requests_File(), {
				f: 'private_group',
				s: 'invite_friends',
				user_id: user_id,
				group_id: group_id
			}, function(data) {
				if (data.status == 200) {
					$('#add-' + user_id).find('button').text('<?php echo $wo['lang']['invited'] ?>');
				}
			});
		}

		function searchUser(self, type) {
			var name = $(self).val(),
				parent = $(self).parents('form:first'),
				SearchResult = parent.find('.search-list');

			if (name != '') {
				$.ajax({
					url: Wo_Ajax_Requests_File(),
					type: 'GET',
					dataType: 'json',
					data: {
						f: 'private_group',
						s: 'search_for',
						name: name,
						type: type
					},
				}).done(function(data) {
					if (data.status == 200) {
						if (data.html.length > 0) {
							SearchResult.parent().addClass('open');
							SearchResult.html(data.html);
						}
					}
				}).fail(function() {})
			} else {
				SearchResult.parent().removeClass('open');

				SearchResult.html('');
				$('#user_id').val(0);
			}
		}

		function Wo_SelectThis(self, val, name) {
			var parent = $(self).parents('form:first'),
				type = parent.data('type');
			SearchResult = parent.find('.search-list');
			SearchResult.parent().removeClass('open');

			SearchResult.html('');
			$('#' + type + '_to').val(name);
			parent.find('#user_id').val(val);
		}

		function Wo_changeReferralStatus(self, type) {
			var referral_id = $('#referral_id').val();

			$('#referral_modal').find('.modal-footer .ball-pulse').fadeIn(100);
			$.ajax({
				url: Wo_Ajax_Requests_File() + '?f=private_group&s=change_referral_status',
				type: 'POST',
				dataType: 'json',
				data: {
					referral_id: referral_id,
					type: type
				}
			}).done(function(data) {
				if (data.status == 200) {
					$('#referral_modal').modal('hide');

					if (type == 'accept') {
						$('#send_thanks_modal').modal('show');
					} else {
						$('#send_forward_modal').modal('show');
					}
				}

				$('#referral_modal').find('.modal-footer .ball-pulse').fadeIn(100);
			})

		}

		var pac_input = document.getElementById('address');
		(function pacSelectFirst(input) {
			// store the original event binding function
			var _addEventListener = (input.addEventListener) ? input.addEventListener : input.attachEvent;

			function addEventListenerWrapper(type, listener) {
				// Simulate a 'down arrow' keypress on hitting 'return' when no pac suggestion is selected,
				// and then trigger the original listener.
				if (type == "keydown") {
					var orig_listener = listener;
					listener = function(event) {
						var suggestion_selected = $(".pac-item-selected").length > 0;
						if (event.which == 13 && !suggestion_selected) {
							var simulated_downarrow = $.Event("keydown", {
								keyCode: 40,
								which: 40
							});
							orig_listener.apply(input, [simulated_downarrow]);
						}
						orig_listener.apply(input, [event]);
					};
				}
				// add the modified listener
				_addEventListener.apply(input, [type, listener]);
			}
			if (input.addEventListener)
				input.addEventListener = addEventListenerWrapper;
			else if (input.attachEvent)
				input.attachEvent = addEventListenerWrapper;
		})(pac_input);

		<?php if ($wo['config']['google_map']) { ?>
			$(function() {
				var autocomplete = new google.maps.places.Autocomplete(pac_input);
			});
		<?php } ?>

		$(function() {
			<?php if (Wo_CanSeeReferral() == true) { ?>
				$('#referral_modal').modal('show');
			<?php } ?>

			$('#send-referral').on('click', function(e) {
				e.preventDefault();

				$('#send_referral_modal').modal('show');
			});

			$('#send_referral_modal').on('hidden.bs.modal', function() {
				$(".blog-alert").html('');
				var SearchResult = $(this).find('.search-list');
				SearchResult.parent().removeClass('open');

				SearchResult.html('');
				$('#referral-reset').click();
			});

			$('form.send_referral_form').ajaxForm({
				url: Wo_Ajax_Requests_File() + '?f=private_group&s=send_referral',
				beforeSend: function() {
					$('.send_referral_form').find('.modal-footer .ball-pulse').fadeIn(100);
				},
				success: function(data) {
					$('.send_referral_form').find('.modal-footer .ball-pulse').fadeOut(100);
					if (data.status == 200) {
						$(".blog-alert").html('<div class="alert alert-success">' + data['message'] + '</div>');
						setTimeout(function() {
							$(".blog-alert").html('');
							$('#referral-reset').click();
							$('#send_referral_modal').modal('hide');
						}, 3000);
					} else {
						var errors = data.errors.join("<br>");
						$(".blog-alert").html('<div class="alert alert-danger">' + errors + '</div>');
						setTimeout(function() {
							$(".blog-alert").html('');
						}, 3000);
					}
				}
			});

			$('#send-thanks').on('click', function(e) {
				e.preventDefault();

				$('#send_thanks_modal').modal('show');
			});

			$('#send_thanks_modal').on('hidden.bs.modal', function() {
				$(".blog-alert").html('');
				var SearchResult = $(this).find('.search-list');
				SearchResult.parent().removeClass('open');

				SearchResult.html('');
				$('#thanks-reset').click();
			});

			$('form.send_thanks_form').ajaxForm({
				url: Wo_Ajax_Requests_File() + '?f=private_group&s=send_thanks',
				beforeSend: function() {
					$('.send_thanks_form').find('.modal-footer .ball-pulse').fadeIn(100);
				},
				success: function(data) {
					$('.send_thanks_form').find('.modal-footer .ball-pulse').fadeOut(100);
					if (data.status == 200) {
						$(".blog-alert").html('<div class="alert alert-success">' + data['message'] + '</div>');
						setTimeout(function() {
							$(".blog-alert").html('');
							$('#thanks-reset').click();
							$('#send_thanks_modal').modal('hide');
						}, 3000);
					} else {
						var errors = data.errors.join("<br>");
						$(".blog-alert").html('<div class="alert alert-danger">' + errors + '</div>');
						setTimeout(function() {
							$(".blog-alert").html('');
						}, 3000);
					}
				}
			});

			$('form.send_forward_form').ajaxForm({
				url: Wo_Ajax_Requests_File() + '?f=private_group&s=resend_referral',
				beforeSend: function() {
					$('.send_forward_form').find('.modal-footer .ball-pulse').fadeIn(100);
				},
				success: function(data) {
					$('.send_forward_form').find('.modal-footer .ball-pulse').fadeOut(100);
					if (data.status == 200) {
						$(".blog-alert").html('<div class="alert alert-success">' + data['message'] + '</div>');
						setTimeout(function() {
							$(".blog-alert").html('');
							$('#forward-reset').click();
							$('#send_forward_modal').modal('hide');
						}, 3000);
					} else {
						var errors = data.errors.join("<br>");
						$(".blog-alert").html('<div class="alert alert-danger">' + errors + '</div>');
						setTimeout(function() {
							$(".blog-alert").html('');
						}, 3000);
					}
				}
			});
		});
	<?php } ?>

	$(function() {
		if ($(window).width() > 600) {
			$(".user-avatar").hover(function() {
				$('.profile-avatar-changer').fadeIn(100);
			}, function() {
				$('.profile-avatar-changer').fadeOut(100);
			});
		}
		if ($(window).width() > 600) {
			$(".user-cover").hover(function() {
				$('.profile-cover-changer').fadeIn(100);
			}, function() {
				$('.profile-cover-changer').fadeOut(100);
			});
		}

		$('form.profile-avatar-changer').ajaxForm({
			url: Wo_Ajax_Requests_File() + '?f=private_group&s=update_group_avatar_picture',
			beforeSend: function() {
				$('.profile_avatar').fadeOut(100);
				$('.user-avatar-uploading-container,.user-avatar-uploading-progress').fadeIn(200);
			},
			success: function(data) {
				$('.profile_avatar').fadeIn(100);
				if (data.status == 200) {
					$('[id^=group-avatar-image]').attr("src", data.img);
				}
				$('.user-avatar-uploading-container, .user-avatar-uploading-progress').fadeOut(200);
			}
		});

		$('form.profile-cover-changer').ajaxForm({
			url: Wo_Ajax_Requests_File() + '?f=private_groups&s=update_group_cover_picture',
			beforeSend: function() {
				$('.profile_cover').fadeOut(100);
				$('.user-cover-uploading-container,.user-cover-uploading-progress').fadeIn(200);
			},
			success: function(data) {
				$('.profile_cover').fadeIn(100);
				if (data.status == 200) {
					$('[id^=cover-image]').attr("src", data.img);
				}
				$('.user-cover-uploading-container,.user-cover-uploading-progress').fadeOut(200);
			}
		});
	});

	function Wo_UpdateProfileAvatar() {
		$("form.profile-avatar-changer").submit();
	}

	function Wo_UpdateProfileCover() {
		$("form.profile-cover-changer").submit();
	}

	function Wo_ReportGroup(id = false, report = true) {
		var report_text = $("#report-group-text-<?php echo $wo['group_profile']['id']; ?>").val();
		if (!id) {
			return false;
		} else if (report == true) {
			if (!report_text) {
				return false;
			}
		}

		$('#report_group').find('.modal-footer .ball-pulse').fadeIn(100);
		$.ajax({
			url: Wo_Ajax_Requests_File() + '?f=private_group&s=report_group',
			type: 'POST',
			dataType: 'json',
			data: {
				text: report_text,
				group: id
			}
		}).done(function(data) {
			if (data.status == 200 && data.code == 0) {
				$('#report_status').replaceWith('\
                <li id="report_status" class="list-group-item pointer" onclick="$(\'#report_group\').modal(\'show\');">\
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12" y2="17"></line></svg>\
                    <span><?php echo $wo['lang']['report_group']; ?></span>\
                </li>');
			} else if (data.status == 200 && data.code == 1) {
				$("#report-group-text-<?php echo $wo['group_profile']['id']; ?>").val('');
				$("#report_group").modal('hide');
				$('#report_status').replaceWith('\
                <li id="report_status" class="list-group-item pointer" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,false);">\
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12" y2="17"></line></svg>\
                    <span><?php echo $wo['lang']['unreport']; ?></span>\
                </li>');
			}
			$('#report_group').find('.modal-footer .ball-pulse').fadeOut(100);
		}).fail(function() {
			console.log("error");
		})
	}
</script>