<?php if($wo['mediafilelist']->user){  ?>
    <tr class="user-list" id="ReceiptID_<?php echo $wo['mediafilelist']->id?>" data-receipt-id="<?php echo $wo['mediafilelist']->id?>" style="width: 25%; float: left;margin-top: 20px;">
        <td style="border: 0px;text-align: center;display: block;">
            <a href="<?php echo $wo['site_url'] . '/@' . $wo['mediafilelist']->user['username']; ?>" target="_blank">
                <img src="<?php echo $wo['mediafilelist']->user['avatar'];?>" class="setting-avatar" alt="<?php echo $wo['mediafilelist']->user['username'];?> Profile Picture">
                <?php echo $wo['mediafilelist']->user['name']; ?>
            </a>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <span style="color:#607D8B;font-size: 11px;font-weight: bold;" class=" ajax-time" title="<?php echo date('c', strtotime($wo['mediafilelist']->created_at)); ?>">
        </span>
            <hr>
<!--            <a href="--><?php //echo Wo_GetMedia($wo['mediafilelist']->receipt_file); ?><!--" target="_blank" >-->
<!--                <img src="--><?php //echo Wo_GetMedia($wo['mediafilelist']->receipt_file); ?><!--" class="setting-avatar" style="min-width: 197px;object-fit: cover;height: 250px;">-->
<!--            </a>-->
            <div class="col-12">
                <strong>Name :</strong><span><?php echo $wo['mediafilelist']->service_name;?></span><br>
                <strong>Tags/ Keyword :</strong><span><?php echo $wo['mediafilelist']->tag_keyword;?></span><br>
                <strong>Group Category :</strong><span><?php echo $wo['mediafilelist']->group_category;?></span><br>
                <strong>Job Category :</strong><span><?php echo $wo['mediafilelist']->job_category;?></span><br>
                <strong>Service Location :</strong><span><?php echo $wo['mediafilelist']->service_location;?></span><br>
                <strong>Details :</strong><span><?php echo $wo['mediafilelist']->details;?></span><br>
            </div>
            <div class="clearfix"></div>
            <p><b><?php //echo $wo['mediafilelist']->mode;?></b></p>
            <p>
                <strong>Budget :</strong> =
                <b><?php echo Wo_GetCurrency($wo['config']['currency']) . $wo['mediafilelist']->budget;?></b>
            </p>
            <?php if((int)$wo['mediafilelist']->approved == 0){?>
            <div class="row">
                <div class="col-md-6">
                    <button  style="float: right;" onclick="Wo_DeleteLead(<?php echo $wo['mediafilelist']->id?>,<?php echo $wo['mediafilelist']->user_id?>);" type="button" class="btn btn-danger waves-effect waves-light" style="margin: 0 auto;display: block;">DELETE</button>
                </div>
                <div class="col-md-6">
                    <button style="float: left;" onclick="Wo_ApproveLead(<?php echo $wo['mediafilelist']->id?>);" type="button" class="btn btn-success waves-effect waves-light" style="margin: 0 auto;display: block;">APPROVE</button>
                </div>
            </div>
            <?php } else{ ?>
        <b style="color:darkgreen;">Approved <?php echo Wo_Time_Elapsed_String($wo['mediafilelist']->approved_at); ?></b>
    <?php } ?>
        </td>
    </tr>
<?php } ?>