<div class="container-fluid">
    <div class="block-header">
        <h2>Pro Users > Manage Pro Users </h2>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Pro Users</h2>
                </div>
                <div class="body">
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Package Name</th>
                                <th>Package</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
<?php $sections = Wo_GetProUsers(array('forums'=>false, 'limit'=>500000, 'order_by' => 'DESC')) ?>
<?php foreach ($sections as $section): ?>
    <tr data-rmd-section-ident="<?php echo $section['user_package_id']; ?>">
        <td><?php echo $section['user_package_id']; ?></td>
        <td><?php echo $section['username']; ?></td>
        <td><?php echo $section['name']; ?></td>
        <td><?php echo $section['user_status']; ?></td>
        <td>
            <button class="btn btn-success delete-section waves-effect waves-light" id="<?php echo $section['user_package_id'];?>">
                Approve
            </button>
            <button class="btn btn-danger disaprove-section waves-effect waves-light" id="<?php echo $section['user_package_id'];?>">
                Dis-Approve
            </button>
        </td>
    </tr>
<?php endforeach;?>
</tbody>
</table>
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
</div>
</div>
<!-- #END# Vertical Layout -->
<div class="modal fade" id="delete-section">
<div class="modal-dialog">
<div class="modal-content modal-col-red">
<div class="modal-header">
<h4 class="modal-title"><i class="fa fa-exclamation-circle"></i> Approve User</h4>
</div>
<div class="modal-body">
<p>Are you sure you want to Approve the User?</p>
</div>
<div class="modal-footer">
<button  type="button" onclick="Wo_ApproveUser($('#delete-section').attr('data-section-ident'))" class="btn btn-link">Approve</button>
<button  type="button" class="btn btn-link" data-dismiss="modal">CLOSE</button>
</div>
</div>
</div>
</div>
<!-- #END# Vertical Layout -->
<div class="modal fade" id="disaprove-section">
<div class="modal-dialog">
<div class="modal-content modal-col-red">
<div class="modal-header">
<h4 class="modal-title"><i class="fa fa-exclamation-circle"></i> Dis-Approve User</h4>
</div>
<div class="modal-body">
<p>Are you sure you want to Dis-Approve the User?</p>
</div>
<div class="modal-footer">
<button  type="button" onclick="Wo_DisApproveUser($('#disaprove-section').attr('data-section-ident'))" class="btn btn-link">Dis-Approve</button>
<button  type="button" class="btn btn-link" data-dismiss="modal">CLOSE</button>
</div>
</div>
</div>
</div>
<script>
$(function () {
$('table').DataTable();
});
$(document).on('click', ".delete-section", function(event) {
event.preventDefault();
$("#delete-section").attr('data-section-ident', $(this).attr('id')).modal('show');
});

$(document).on('click', ".disaprove-section", function(event) {
event.preventDefault();
$("#disaprove-section").attr('data-section-ident', $(this).attr('id')).modal('show');
});
function Wo_ApproveUser(id) {
if (!id) {
return false;
} else {
$("#delete-section").modal("hide");
$("[data-rmd-section-ident='" + id + "']").slideUp(function() {
$(this).remove()
});
$.ajax({
type: "GET",
url: Wo_Ajax_Requests_File(),
data: {
id: id,
f: 'approve_user'
},
dataType: 'json'
});
}
}

function Wo_DisApproveUser(id) {
if (!id) {
return false;
} else {
$("#disaprove-section").modal("hide");
$("[data-rmd-section-ident='" + id + "']").slideUp(function() {
$(this).remove()
});
$.ajax({
type: "GET",
url: Wo_Ajax_Requests_File(),
data: {
id: id,
f: 'disapprove_user'
},
dataType: 'json'
});
}
}
</script>

