<div class="page-margin">
    <div class="row">
        <div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
        <div class="col-md-7 middlecol wo-create-forms">
            <?php $invite_time = $wo['invitation_profile']['time']; ?>

            <div class="wo_settings_page">
                <div class="sun_head_onboard shortpwidth group">
                    <img class="sho_img" src="<?php echo $wo['config']['theme_url']; ?>/img/cads/group.svg" alt="<?php echo $wo['lang']['group'] ?>" />
                    <div class="sun_head_onboard_innr">
                        <h2><?php echo $wo['lang']['join_group']; ?></h2>
                    </div>
                </div>

                <form class="create-group-form form-horizontal" method="post">
                    <div class="setting-panel row">
                        <!-- Text input-->

                        <div class="form-group col-lg-12">
                            <label class="col-md-12" for="job_category"><?php echo $wo['lang']['job_category']; ?> *</label>
                            <div class="col-md-12">
                                <select name="job_category" id="job_category" class="form-control">
                                    <option value=""><?php echo $wo['lang']['select'] ?></option>
                                    <?php if (!empty($wo['allowed_categories'])) {
                                        foreach ($wo['allowed_categories'] as $category_id => $category_name) { ?>
                                            <option value="<?php echo $category_id ?>"><?php echo $category_name; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <?php $show = true;
                        $payedData = Wo_GetUserPaymentStatus('join');
                        if (!empty($payedData)) {
                            $show = false;
                            $payment_id = $payedData;
                        } ?>

                        <?php if ($show) { ?>
                            <div class="form-group col-lg-12 row bank-row" style="display: flex; align-items: center">
                                <div class="col-md-7">
                                    <?php $orginal_txt  = array(
                                        "{currency}",
                                        "{amount}"
                                    );
                                    $replaced_txt = array(
                                        Wo_GetCurrency($wo['config']['currency']),
                                        $wo['config']['joining_fee']
                                    );
                                    echo str_replace($orginal_txt, $replaced_txt, $wo['lang']['joining_fee']); ?>
                                </div>

                                <div class="col-md-5 text-right">
                                    <button type="button" class="btn btn-main setting-panel-mdbtn" onclick="();"><?php echo $wo['lang']['pay']; ?></button>
                                </div>
                            </div>
                        <?php } ?>

                    </div>
                    <div class="app-general-alert setting-update-alert"></div>
                    <div class="form-group last-sett-btn modal-footer">
                        <div class="ball-pulse">
                            <div></div>
                            <div></div>
                            <div></div>
                        </div>
                        <button type="submit" class="btn btn-main setting-panel-mdbtn"><?php echo $wo['lang']['create']; ?></button>
                    </div>

                    <input type="hidden" name="payment_id" id="payment_id" value="<?php echo (!$show) ? $payment_id : "" ?>">
                    <input type="hidden" name="group_id" id="group_id" value="<?php echo $wo['group_profile']['id'] ?>">
                    <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                </form>
            </div>
        </div>
        <!-- .col-md-8 -->
        <?php echo Wo_LoadPage('sidebar/content'); ?>
    </div>
    <!-- .row -->
</div>
<?php if ($show) { ?>
    <div id="pay-modal"></div>
    <?php if ($show) { ?>
        <div id="pay-modal"></div>
        <div class="modal fade" id="bank_transfer_modal" role="dialog" data-keyboard="false" style="overflow-y: auto;">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
                                    <line x1="18" y1="6" x2="6" y2="18"></line>
                                    <line x1="6" y1="6" x2="18" y2="18"></line>
                                </svg></span></button>
                        <h4 class="modal-title"><?php echo $wo['lang']['bank_transfer'] ?></h4>
                    </div>
                    <form class="form form-horizontal" method="post" id="bank_transfer_form" action="#">
                        <div class="modal-body dt_bank_trans_modal">
                            <div id="blog-alert"></div>

                            <?php echo $wo['config']['bank_description']; ?>

                            <?php if (!empty($wo['config']['bank_transfer_note'])) { ?>
                                <div class="dt_user_profile hide_alert_info_bank_trans">
                                    <span class="valign-wrapper">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                            <path fill="currentColor" d="M13,13H11V7H13M13,17H11V15H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                                        </svg> Note:
                                    </span>
                                    <ul class="dt_prof_vrfy">
                                        <li><?php echo $wo['config']['bank_transfer_note']; ?></li>
                                    </ul>
                                </div>
                            <?php } ?>
                            <p class="dt_bank_trans_upl_rec"><a href="javascript:void(0);" onclick="$('#bank_transfer_modal').addClass('up_rec_active'); return false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                        <path fill="currentColor" d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M13.5,16V19H10.5V16H8L12,12L16,16H13.5M13,9V3.5L18.5,9H13Z"></path>
                                    </svg> <?php echo $wo['lang']['upload'] ?></a></p>
                            <div class="upload_bank_receipts">
                                <div onclick="document.getElementById('thumbnail').click(); return false">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                        <path fill="currentColor" d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M13.5,16V19H10.5V16H8L12,12L16,16H13.5M13,9V3.5L18.5,9H13Z"></path>
                                    </svg>
                                    <p><?php echo $wo['lang']['browse_to_upload']; ?></p>
                                    <img id="receipt_img_preview" src="">
                                </div>
                            </div>
                            <input type="file" class="hidden" id="thumbnail" name="thumbnail" accept="image/*">
                            <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                            <input name="image" type="file" id="upload" class="hidden">
                            <input name="type" type="hidden" id="bank_transfer_type" class="hidden">
                            <input type="reset" id="configreset" value="Reset" class="hidden">
                        </div>
                        <div class="modal-footer">
                            <div class="ball-pulse">
                                <div></div>
                                <div></div>
                                <div></div>
                            </div>
                            <button type="submit" class="btn btn-main btn-mat"><?php echo $wo['lang']['publish']; ?></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    <?php } ?>
<?php } ?>

<!-- .page-margin -->
<script type="text/javascript">
    <?php if ($show) { ?>

        function Wo_GetPaymentLink() {
            $.get(Wo_Ajax_Requests_File() + '?f=private_group&s=get_private_payment_method&type=join', function(data) {
                if (data.status == 200) {
                    $('#pay-modal').html(data.html);
                    $('#pay-private').modal({
                        show: true
                    });
                }
            });
        }

        function Wo_CheckOutCard(type, amount, payment_type) {
            $('#configreset').click();
            $("#blog-alert").html('');
            $('#bank_transfer_type').val(type);
            $('#pay-private').modal('hide');
            $('#bank_transfer_modal').modal({
                show: true
            });
        }
    <?php } ?>

    $(function() {
        $(document).on('change', '#thumbnail', function(event) {
            let imgPath = $(this)[0].files[0].name;
            if (typeof(FileReader) != "undefined") {
                let reader = new FileReader();
                reader.onload = function(e) {
                    $('#receipt_img_preview').attr('src', e.target.result);
                }
                reader.readAsDataURL(this.files[0]);
            }
            $('#bank_transfer_modal').addClass('up_rec_img_ready');
        });

        $('#bank_transfer_form').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=private_group&s=bank_transfer',
            beforeSend: function() {
                $('#bank_transfer_form').find('.ball-pulse').fadeIn(100);
            },
            success: function(data) {
                if (data['status'] == 200) {
                    $('.bank-row').remove();
                    $('#payment_id').val(data['p_id']);
                    $("#blog-alert").html('<div class="alert alert-success">' + data['message'] + '</div>');
                    setTimeout(function() {
                        $('#bank_transfer_modal').removeClass('up_rec_active');
                        $(".prv-img").html('<div class="thumbnail-rendderer"><div><h4 class="bold"><?php echo $wo['lang']['drop_img_here']; ?></h4><div class="error-text-renderer"></div><div><span><?php echo $wo['lang']['or']; ?></span><p><?php echo $wo['lang']['browse_to_upload']; ?></p></div></div> </div>');
                        $("#blog-alert").html('');
                        $('#configreset').click();
                        $('#bank_transfer_modal').modal('hide');

                    }, 3000)
                } else if (data['message']) {
                    $("#blog-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
                }
                $('#bank_transfer_form').find('.ball-pulse').fadeOut(100);
            }
        });

        $('form.join-group-form').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=private_group&s=join_group',
            beforeSend: function() {
                $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
            },
            success: function(data) {
                scrollToTop();
                $('.app-general-alert').html('');

                if (data.status == 200) {
                    $('.app-general-alert').html('<div class="alert alert-success">' + data.message + '</div>');
                    $('.alert-success').fadeIn(300);
                } else {
                    var errors = data.errors.join("<br>");
                    $('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
                    $('.alert-danger').fadeIn(300);
                }
                $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
            }
        });
    });
</script>